starknet-io/starknet-docs

- docs/Blocks/header.md
> docs: Readd block header

- docs/intro.md
- docusaurus.config.js
- src/config/home.json
- src/pages/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/17)
> docs: front page

- docs/CLI/commands.md
OpenZeppelin's name was written incorrectly. This PR fixes that typo.
> docs: Fixed typo in OpenZeppelin's name.

- docs/Blocks/transactions.md
- docs/Contracts/contract-classes.md
- docs/State/starknet-state.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/36)
> docs: contact classes

- docs/L1<>L2 Communication/token-bridge.md
Fix typo: "bridgs" -> "bridges"
> docs: Fix typo on "bridgs"

- build_local_site.sh
- linked-worktree-as-content-source.js
Added an Antora extension file to enable using Git worktrees. Added a build script that runs the necessary command line option to enable the extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/80)
> [feat] Added an Antora extension file to enable using Git worktrees.

- components/StarkNet/modules/ROOT/pages/Ecosystem/con_block_explorers.adoc
Fixing a typo
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/87)
> fix: typo in Block Explorers--Viewblock should be ViewBlock

- components/StarkNet/modules/ROOT/nav.adoc
- components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc
Added StarkNet operational info.
https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/Ecosystem/ref_operational_info/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)
> docs: Added operational info

- components/StarkNet/modules/develop/nav.adoc
- components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc
The StarkNet compiler will be updated soon for Cairo 1.0/regenesis, so in order not to spend much time on something that will be obsolete within 3-6 months, this task is essentially to add the command line help (`starknet-compile --help`) to the docs.
https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/develop/CLI/starknet-compiler-options
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)
> doc: Added option reference for `starknet-compile`.

- .htaccess
﻿There was some change to the syntax of the URL over time (before the move to Antora). The Google result uses this
docs/L1<b><></b>L2 Communication/token-bridge, while the one that was in the redirect had this:
docs/L1-L2 Communication/token-bridge
Now it includes both.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/95)
> [Fix] Added permutation of token-bridge URL to redirect file

- README.adoc
Updating release instructions to use `git rebase` instead of `git merge`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/103)
> chore: Updating release instructions to use `git rebase` instead of `git merge`

- components/StarkNet/modules/architecture_and_concepts/pages/Blocks/header.adoc
- components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
- components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-hash.adoc
The formatting of the mathematical notations in [Blocks](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/header/) is broken (image below). Fixed that and some properly placed quotations in [Transaction structure](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/244)
> fix: badly formatted mathematical notation in blocks

- components/StarkNet/modules/architecture_and_concepts/pages/Hashing/hash-functions.adoc
add Poseidon hash specs
https://starknet-io.github.io/starknet-docs/pr-322/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/322)
> add Poseidon hash specs

- components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc
- components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/540)
> Update wording on AA Deploying accounts

- components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
This PR use the correct version in `declare transaction V2` table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/659)
> fix: version in declare transaction V2 table

- contributing_to_docs/doc_guidelines.adoc
- ui/preview-src/fee-mechanism.adoc
- ui/preview-src/starknet-events.adoc
- ui/preview-src/token-bridge.adoc
- ui/preview-src/upcoming_versions.adoc
Fix: typos
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/693)
> fix: typos

- components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
From Oded: We found a mistake in the docs regarding the L1->L2 message hash calculation: max_fee  is not currently part of the hash calculation. Can we please remove it?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/700)
> fix: Remove max_fee from messaging-mechanism.adoc

- components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
Removed image from L1-L2 communication, approved by Shani.
https://starknet-io.github.io/starknet-docs/pr-698/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/698)
> fix: removed image from L1-L2 communication

- components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
- components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
- components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
- components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- components/Starknet/modules/tools/nav.adoc
- components/Starknet/modules/tools/pages/api_rpc.adoc
> Juno updates

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transactions.adoc
Fix order of deploy account hash calculation:
ℎ(class_hash, contract_address_salt, constructor_calldata),
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/767)
> Fix order of deploy account hash calculation

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/775)
> Update declare v0, v1 and v2 hash calc code examples

- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- Removed Starknet v0.12.1 testnet mention since it's a duplicate of the mainnet and looking at the history, we don't have testnet versions. 
- added ids to each version since it creates a cleaner link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/794)
> Update documentation version notes 

- components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
- components/Starknet/modules/quick_start/pages/account_setup.adoc
- components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/799)
> Update all instances of on-chain to onchain

- components/Starknet/modules/quick_start/nav.adoc
- components/Starknet/modules/quick_start/pages/compile_and_deploy.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/828)
> Subitem fix for menu

- components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc
Fixed the formatting of the Ethereum account markdown link to ensure it displays correctly in the preview.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/858)
> docs: markdown link of Ethereum account

- contributing_to_docs/doc_guidelines.adoc
doc_guidelines.adoc: Added section on guidelines for getting peer reviews
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/862)
> chore: Add peer review guidelines to Contribution guidelines

- README.adoc
Instructions for merging dev to master were incorrect. Need to specify:
`git merge origin/dev`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/879)
> Chore: Fix merge instructions in README

- components/Starknet/modules/tools/pages/important_addresses.adoc
Update docs with a note on Goerli Testnet 2 deprecation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/891)
> Update important_addresses.adoc with Goerli 2 deprecation

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
Removed collabsible section for `get_execution_info`
https://starknet-io.github.io/starknet-docs/pr-908/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/908)
> fix: Removed collabsible section for `get_execution_info`

- components/Starknet/modules/ROOT/partials/snippet_important_goerli2_removed.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc
- components/Starknet/modules/starknet_versions/pages/deprecated.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- components/Starknet/modules/tools/pages/important_addresses.adoc
Goerli 2 is no longer supported. This PR removes all mention of Goerli 2, except for one admonition announcing it has been removed.
[Important addresses](https://starknet-io.github.io/starknet-docs/pr-919/documentation/tools/important_addresses/)
[Transaction types>ChainID](https://starknet-io.github.io/starknet-docs/pr-919/documentation/architecture_and_concepts/Network_Architecture/transactions/#chain-id)
[Starknet environments](https://starknet-io.github.io/starknet-docs/pr-919/documentation/starknet_versions/version_notes/#starknet_environments)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/919)
> docs: Removed Goerli testnet 2

- components/Starknet/modules/tools/pages/starkgate-adding_a_token.adoc
Added email address to contact for adding a custom bridge to StarkGate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/923)
> docs: Added email address to contact for adding a custom bridge to StarkGate.

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-storage.adoc
Applied new cairo syntax for Contract storage (maybe someone missed these places)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/959)
> fix: Contract storage page is still referring to the old cairo syntax

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/algolia-indexing.yml
- .github/workflows/push.yml
- playbook.yml
This PR removed the `dev` branch from the workflows.
Using a `dev` branch is a normal part of a source code repo, but the docs flow does not require this branch, and it adds an unnecessary step in the release and publishing flow.
The projected plan is to remove dev and merge branches directly to master (which is planned to change to main in the future, consistent with other repos). In a case where a PR should not be published immediately, such as a feature that is not yet released, a release branch is created to hold that content until the official release date. For example, #933.
- - -
This change …
> chore: remove dev branch from workflows

- components/Starknet/modules/ROOT/partials/attributes.adoc
- playbook.yml
This, together with https://github.com/starknet-io/starknet-docs-antora-ui/pull/28, add a header with Starknet version info on the various testnets and Mainnet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/976)
> feat: Add Starknet version to UI header

- .github/workflows/pull_request.yml
Added a workflow to delete old previews upon merging to master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/977)
> chore: Delete previews upon merging to master

- components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/982)
> fix: More minor edits in account interface

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-address.adoc
A `deploy_account` tx v3 has a `contract_address` field, and not `sender_address`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1012)
> Update transactions.adoc with deploy account tx v3 hash calculation

- .gitattributes
Github uses linguist to detect the languages used in a repo for statistical purposes and to show on the repo's home page.
OnlyDust links to this info for the project's stats.
This file should make AsciiDoc visible to linguist, so that ultimately OnlyDust will show it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1053)
> chore: Add .gitattributes file to enable linguist to identify that AsciiDoc and .yml are used in this repo.

- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1066)
> fix: Date and percentages in RN

- components/Starknet/modules/architecture_and_concepts/nav.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-syntax.adoc
Updated tabbed examples to Cairo v1/Cairo v2
[Migrating a contract from Cairo v1 to Cairo v2](https://starknet-io.github.io/starknet-docs/pr-1072/documentation/architecture_and_concepts/Smart_Contracts/contract-syntax/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1072)
> fix: Update tab labels of examples from Cairo v1 to Cairo v2

- components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc
updated old link to example contracts folder
Link to example contracts is not found - 404. I updated it to the new examples folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1077)
> fix: Update declare_a_smart_contract.adoc

- components/Starknet/modules/tools/pages/audit.adoc
This PR adds OtterSec and Beosin to the Audit providers page. These two Companies are already added on the starknet.io official website.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1075)
> Docs: Add OtterSec and Beosin to audit providers

- components/Starknet/modules/tools/nav.adoc
- components/Starknet/modules/tools/pages/starkgate-removing_a_token.adoc
- components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
Remove info on removing a token.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1079)
> docs: Remove info on removing a token

- README.adoc
- contributing_to_docs/doc_guidelines.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1085)
> Updates to contribution guidelines

- components/Starknet/modules/quick_start/pages/set_up_an_account.adoc
Minor edits to Setting up an account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1070)
> [fix] Minor edits to Setting up an account

- components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
1. Update starkgate's references
2. Delete the L1 Constant `MIN_DEPLOYMENT_FEE`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1081)
> docs: update starkgate_function_reference.adoc

- components/Starknet/modules/architecture_and_concepts/nav.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc
Changed title to **Contract classes and instances** in contract-classes.adoc, and addresses #1098.
[Contract classes and instances](https://starknet-io.github.io/starknet-docs/pr-1099/documentation/architecture_and_concepts/Smart_Contracts/contract-classes/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1099)
> docs: Describe contract nonce. Changed title to Contract classes and instances in contract-classes.adoc

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
Adjusting the fee formula to account for the fee token address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1123)
> fix: ignore fee token contract is the fee formula

- components/Starknet/modules/tools/pages/limits_and_triggers.adoc
A couple of fixes and additions to current limits.
TBD: Descriptions for **Signature length (felts)** and **Calldata length (felts)**.
[Current limits](https://starknet-io.github.io/starknet-docs/pr-1136/documentation/tools/limits_and_triggers/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1136)
> Updates to current limits.

- components/Starknet/modules/tools/pages/important_addresses.adoc
Add addresses for L2 STRK and vSTRK.
[Starknet contracts and sequencer addresses](https://starknet-io.github.io/starknet-docs/pr-1137/documentation/tools/important_addresses/)
> doc: Add addresses for L2 STRK and vSTRK.

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc
Added a note that if a transaction is rejected, then another transaction with the same transaction hash cannot be sent.
https://starknet-io.github.io/starknet-docs/pr-1141/documentation/architecture_and_concepts/Network_Architecture/transaction-life-cycle/
> Update transaction-life-cycle.adoc with a note on rejected transactions

- _typos.toml
Adding this fix from @xiaolou86 from PR#1097, which has other changes that are taking longer to get reviewed.
> fix: Ignore "afe" when checking for typos. (from xiaolou86 in PR#1097)

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc
Clarifying which type of validation is run on which type of transaction, and that the same validation is run during the mempool stage and the sequencer stage.
> fix: Update validation info in transaction_lifecycle.adoc

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc
- playbook.yml
Working on improving callout format.
[v0.11.0 example of onchain data](https://starknet-io.github.io/starknet-docs/pr-1006/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/#v0.11.0_example)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1006)
> feat: Added callouts to example in Data availability topic.

- components/Starknet/modules/ROOT/partials/snippet_important_goerli2_removed.adoc
- components/Starknet/modules/starknet_versions/pages/deprecated.adoc
Remove support for Starknet CLI, added date for Goerli removal.
[Starknet release notes](https://starknet-io.github.io/starknet-docs/pr-1154/documentation/starknet_versions/version_notes/)
[Deprecated, unsupported, and removed features](https://starknet-io.github.io/starknet-docs/pr-1154/documentation/starknet_versions/deprecated/)
> docs: Update date of Goerli removal, Starknet CLI, in deprecated.adoc

- README.adoc
Change Github to GitHub in the README, that's it.
> docs: minor readme update

- components/Starknet/modules/starknet_versions/nav.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
Release notes taken from https://github.com/starkware-libs/cairo-lang/releases/tag/v0.13.1a0.
[Release notes](https://starknet-io.github.io/starknet-docs/pr-1160/documentation/starknet_versions/version_notes/)
> docs: Update version_notes.adoc with 0.13.1 release notes

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
1. The syscall emit_event example is incorrect, and the problem noted in num 2 also applies here.
2. https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/starknet-events/
The above code emits an event with two keys, the [strings](https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals) “status” and “deposit”
The code shown actually uses “key” and “deposit” as keys
[Events](https://starknet-io.github.io/starknet-docs/pr-1169/documentation/architecture_and_concepts/Smart_Contracts/starknet-events/)
[emit_event](https://starknet-io.github.io/starknet-docs/pr-1169/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/#emit_event)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> fix: Fix example in emit_events

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1174)
> fix: add felt size multiplier to data gas usage

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc
* Minor edits
* Added Description and Keywords metadata to improve SEO.
[Class hash](https://starknet-io.github.io/starknet-docs/pr-1176/documentation/architecture_and_concepts/Smart_Contracts/class-hash/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1176)
> docs: Add metadata to class-hash.adoc

- .github/workflows/pull_request.yml
PR #1097 introduced a security vulnerability. Reverting them until we figure out a secure way to do what we want to do.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1182)
> chore: Revert PRs #1097, #1152.

- components/Starknet/modules/tools/nav.adoc
- components/Starknet/modules/tools/pages/dai_token_migration.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1181)
> docs: Add new topic on migrating from DAI v0 to DAI.

- .github/workflows/push.yml
There is a step in push.yml that is not succeeding. It seems to just create a version tag. Upon creating the version tag, the tag.yml workflow runs. The last step in this workflow, after creating a Release, is to upload the site to the prod server.
Given that we wanted to remove the tag and release workflows from this repo anyway, I moved the upload step directly to the push.yml workflow, and skip the step to create a new version tag and new release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix: Upload to prod server not working

- .github/workflows/push.yml
* Move steps to generate and upload site to production server from tag.yml to push.yml, avoiding tag.yml.
* Comment out step named `Push to remove branch`, which seems to just create a new tag named v0.x.y.
* Move steps to generate and upload site to production server from tag.yml to push.yml, avoiding tag.yml.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1186)
> fix: Remove release steps

- components/Starknet/modules/tools/pages/limits_and_triggers.adoc
New block limits after increasing block size. 
[Current limits](https://starknet-io.github.io/starknet-docs/pr-1188/documentation/tools/limits_and_triggers/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1188)
> docs: Update limits_and_triggers.adoc with new block limits

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
The current documentation does not correctly price l2 --> l1 messages. Messages are not discounted with the storage update discounts, and also have another associated event emission cost, which is now added to the docs.
https://starknet-io.github.io/starknet-docs/pr-1192/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1192)
> docs: fix l2 --> l1 message pricing

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/header.adoc
Updated the block header page in accordance with the latest [json-rpc version](https://github.com/starkware-libs/starknet-specs/blob/4233164155b8a279b408b9638c34db2602b5cdc0/api/starknet_api_openrpc.json#L1436)
https://starknet-io.github.io/starknet-docs/pr-1187/documentation/architecture_and_concepts/Network_Architecture/header/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1187)
> docs: update block header w.r.t Starknet 0.13.1

- components/Starknet/modules/tools/pages/api-services.adoc
Adding QuickNode to the list of API providers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1193)
> docs: Update api-services.adoc with QuickNode

- components/Starknet/modules/architecture_and_concepts/pages/Accounts/account_functions.adoc
Add signatures for `__execute__`, `__validate__` and `__validate_declare__`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1200)
> docs: Add signatures for `__execute__`, `__validate__` and `__validate_declare__`

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/header.adoc
Fix description of `transaction_commitment` in Block structure.
[Block structure](https://starknet-io.github.io/starknet-docs/pr-1211/documentation/architecture_and_concepts/Network_Architecture/header/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1211)
> fix: Updates to `transaction_commitment` in Block structure.

- components/Starknet/modules/ROOT/partials/snippet_important_goerli2_removed.adoc
- components/Starknet/modules/ROOT/partials/snippet_important_goerli_removed.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Accounts/universal-deployer.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc
- components/Starknet/modules/cli/pages/starkli.adoc
- components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc
- components/Starknet/modules/quick_start/pages/deploy_a_smart_contract.adoc
- components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc
- components/Starknet/modules/starknet_versions/pages/deprecated.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- components/Starknet/modules/tools/pages/bridged_tokens.adoc
- components/Starknet/modules/tools/pages/important_addresses.adoc
- components/Starknet/modules/tools/pages/limits_and_triggers.adoc
- components/Starknet/modules/tools/pages/starkgate-bridge.adoc
- playbook.yml
Updated to remove Goerli.
Based on this announcement from yesterday, April 2, 2024:
>Following the mass exodus of Ethereum Goerli validators and the utter inactivity of Starknet Goerli over the last day, Starknet Goerli testnet will be shutting down later today to avoid maintaining an inactive network. Sepolia testnet awaits with open arms. See you there!
**Please use the Files changed tab or Reviewable to see what has been removed.** I only included links to specific pages where it is easy to view the changes, but the site preview does not show what was changed or removed, only how the site will appear when published.
* [Current limits](https://starknet-io.github.io/starknet-docs/pr-1212/documentation/tools/limits_and_triggers/)
* Footer: 
* [Release …
> docs: Updated to remove Goerli.

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc
The leaf hash in the contract trie is not computed using the standard pedersen array hashing defined here https://docs.starknet.io/documentation/architecture_and_concepts/Cryptography/hash-functions/#pedersen_array_hash (impl here : https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/hash_state.py#L6 )
See : https://github.com/eqlabs/pathfinder/blob/d93f50052b6b7b22072de53f0d94e1e74fbe8247/crates/merkle-tree/src/contract_state.rs#L129-L135
This is confusing and should be precised. 
Thank you
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1214)
> Precise the pedersen hash construction for contract trie. 

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- components/Starknet/modules/tools/pages/limits_and_triggers.adoc
- playbook.yml
Updates for 0.13.1.1 (testnet)
[Release notes](https://starknet-io.github.io/starknet-docs/pr-1208/documentation/starknet_versions/version_notes/)
[Gas and transaction fees > L2 payloads: calldata, events, and code](https://starknet-io.github.io/starknet-docs/pr-1208/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/#l2_calldata)
[Current limits](https://starknet-io.github.io/starknet-docs/pr-1208/documentation/tools/limits_and_triggers/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1208)
> docs: Updates for 0.13.1.1 (testnet)

- components/Starknet/modules/ROOT/partials/snippet_important_goerli_removed.adoc
Remove wording from pre-April 11 2024.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1222)
> docs: Update snippet_important_goerli_removed.adoc

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-address.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
Clarify `deployer_address`, including `deploy_from_zero`.
[Contract address](https://starknet-io.github.io/starknet-docs/pr-1234/documentation/architecture_and_concepts/Smart_Contracts/contract-address/)
[deploy](https://starknet-io.github.io/starknet-docs/pr-1234/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/#deploy)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1234)
> fix: Explain `deployer_address`

- components/Starknet/modules/ROOT/nav.adoc
- components/Starknet/modules/ROOT/pages/notational-conventions.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Cryptography/hash-functions.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc
This PR adds a page describing notational conventions in the docs.
[Notational conventions](https://starknet-io.github.io/starknet-docs/pr-1242/documentation/notational-conventions)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1242)
> docs: Add Notational conventions topic

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc
The on-chain data page was not updated since v0.13.1, we add a section that contains some information about blobs
https://starknet-io.github.io/starknet-docs/pr-1247/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1247)
> docs: add eip4844 info to the on-chain data page

- components/Starknet/modules/tools/nav.adoc
- components/Starknet/modules/tools/pages/bridged_tokens.adoc
- components/Starknet/modules/tools/pages/starkgate-bridge.adoc
Readers repeatedly ask for the addresses for StarkGate bridge and supported tokens. This PR clarifies how to find the json files that include that information.
[Bridged tokens](https://starknet-io.github.io/starknet-docs/pr-1241/documentation/tools/bridged_tokens/)
[Supported tokens and token addresses in StarkGate](https://starknet-io.github.io/starknet-docs/pr-1241/documentation/tools/starkgate-bridge/#starkgate_supported_tokens)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1241)
> docs: Clarify how to find StarkGate bridge and token addresses in block explorers

- components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
ref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions
before:
after:
https://starknet-io.github.io/starknet-docs/pr-1271/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1271)
> fix: admonitions

- components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc
Current invoke tx v3 hash calculation has
```
h(
h(account_deployment_data),
h(calldata)
)
```
as part of the hash calculation, though the hash is calculated without the nested hash function. Just
```
h(account_deployment_data),
h(calldata)
```
https://starknet-io.github.io/starknet-docs/pr-1276/documentation/architecture_and_concepts/Network_Architecture/transactions/#v3_hash_calculation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1276)
> Fix invoke tx v3 hash calculation

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/messaging-mechanism.adoc
Topic describes L1-L2 messaging as being "cross-chain". This might be confusing, so this PR changes that to "cross-layer"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1289)
> fix: Change "cross-chain" to "cross-layer" in L1-L2 Messaging mechanism

- playbook.yml
Removing dev survey banner, and switching back to `main` branch of starknet-docs-antora-ui, which now includes the contributors at the top of each page. from https://github.com/starknet-io/starknet-docs-antora-ui/pull/39.
This feature is a response to issue #1042 *Add list of contributors*. It adds the following:
* The date and time the page was last edited, and by whom.
* A button that shows all contributors for each published page.
A big **Thank You** and shoutout to @xiaolou86 for implementing this functionality! :1st_place_medal: :tada: :man_dancing: 
https://starknet-io.github.io/starknet-docs/pr-1306/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1306)
> feat: Remove dev survey banner; include list of contributors at the top of each page

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
Link to the recommended way to translate the response of `starknet_estimateFee` call to the different fields of `resource_bounds` when sending txs v3.
[Transaction v3 Fee Estimation](https://starknet-io.github.io/starknet-docs/pr-1296/architecture-and-concepts/network-architecture/transactions/#v3-fee-estimation)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1296)
> docs: Update transactions.adoc with txs v3 fee estimation

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transaction-life-cycle.adoc
DEPLOY_ACCOUNT and DECLARE transactions cannot be reverted. Added a note about this.
[Transaction status](https://starknet-io.github.io/starknet-docs/pr-1295/architecture-and-concepts/network-architecture/transaction-life-cycle/#transaction_status)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1295)
> Update transaction-life-cycle.adoc with finality status of deploy_account and declare transactions

- components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
Added warnings regarding important validations that should manually be added to `__execute__`.
Slightly refactored the page, and removed most of the last section since the function's signatures don't add new information.
https://starknet-io.github.io/starknet-docs/pr-1302/architecture-and-concepts/accounts/account-functions/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1302)
> docs: add validate warnings and refactor the account's functions page

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/serialization-of-cairo-types.adoc
Indexes were wrong.
(https://starknet-io.github.io/starknet-docs/pr-1307/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1307)
> docs: indexes fix in serialization-of-cairo-types 

- components/Starknet/modules/tools/pages/devtools.adoc
The doc says "starknet-go" but the real name is "starknet.go". This PR fixes that.
https://starknet-io.github.io/starknet-docs/pr-1319/
https://docs.starknet.io/tools/devtools/#sdks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1319)
> fix: starknet.go name in docs

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/serialization-of-cairo-types.adoc
Fixing the examples of enum serialization is the "serialization of cairo types" page. Indexing of variants for Serde is always 0-based.
https://starknet-io.github.io/starknet-docs/pr-1343/architecture-and-concepts/smart-contracts/serialization-of-cairo-types/#serialization_of_enums
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1343)
> fix: enum variants serialization

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/serialization-of-cairo-types.adoc
Bugfix: Fix an incorrect serialization output in Table 3.
The correct serialization output should be:
[2,0,5,3,1,2,3]
https://docs.starknet.io/architecture-and-concepts/smart-contracts/serialization-of-cairo-types/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1335)
> fix: incorrect serialization output in serialization-of-cairo-types.adoc

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
Fixes the wrong DEPLOY_ACCOUNT_TXN version in docs. There is no V0 DEPLOY_ACCOUNT_TXN, the correct one is V1.
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2226
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1339)
> Fixes wrong DEPLOY_ACCOUNT_TXN version

- components/Starknet/modules/ROOT/pages/index.adoc
Removed developer tools and resources from overview.
https://starknet-io.github.io/starknet-docs/pr-1378/
> Removed developer tools and resources from overview

- components/Starknet/modules/staking/pages/architecture.adoc
Removed the operator from staking/architecture.adoc
https://starknet-io.github.io/starknet-docs/pr-1382/staking/architecture/
> Removed the operator from staking's architecture

- components/Starknet/modules/staking/pages/entering-staking.adoc
Added Staking dashboard registration links to entering-staking.adoc.
https://starknet-io.github.io/starknet-docs/pr-1385/staking/entering-staking/
> Staking dashboard registration links addition

- components/Starknet/modules/staking/pages/claiming-rewards.adoc
Got rid of operator contract in claiming-rewards.adoc.
https://starknet-io.github.io/starknet-docs/pr-1386/staking/claiming-rewards/
> Staking operator removal (claiming-rewards.adoc)

- components/Starknet/modules/staking/pages/managing-staking-and-delegation-operations.adoc
Got rid of the Operator contract in managing-staking-and-delegation-operations.adoc.
https://starknet-io.github.io/starknet-docs/pr-1388/staking/managing-staking-and-delegation-operations/
> Stacking operator removal (managing-staking-and-delegation-operations.adoc)

- components/Starknet/modules/staking/pages/overview.adoc
Got rid of the Operator contract from staking/overview.adoc.
https://starknet-io.github.io/starknet-docs/pr-1389/staking/overview/
> Staking operator removal (overview.adoc)

- components/Starknet/modules/starkgate/pages/overview.adoc
I updated the links to the tokens lists on mainnet and sepolia to the json files that contain all the tokens.
https://starknet-io.github.io/starknet-docs/pr-1381/starkgate/overview/
> chore: replacing links to tokens lists to updated ones

- components/Starknet/modules/staking/pages/entering-staking.adoc
Fix 404 for system requirement of Madara in Starknet staking guide
This pull request includes a minor update to a document in the `components/Starknet/modules/staking/pages/entering-staking.adoc` file. The change corrects a URL in the Madara node implementation documentation link.
* Corrected the URL for the hardware requirements of the Madara node implementation in the staking documentation. (`components/Starknet/modules/staking/pages/entering-staking.adoc`)
https://starknet-io.github.io/starknet-docs/pr-1404/staking/entering-staking/
> fix: Fix 404 for system requirement of Madara in Starknet staking guide

- components/Starknet/modules/staking/pages/entering-staking.adoc
Fixed phrasing of links to dashboards in "Becoming a Validator".
https://starknet-io.github.io/starknet-docs/pr-1412/staking/entering-staking/
> Fixed phrasing in "Becoming a Validator"

- components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc
Refactored "Declaring a smart contract", also addressing #1359 and #1406. 
https://starknet-io.github.io/starknet-docs/pr-1416/quick-start/declare-a-smart-contract/
> "Declaring a smart contract" refactor

- components/Starknet/modules/staking/pages/entering-staking.adoc
Corrected the link to Argent's HW wallet setup.
https://starknet-io.github.io/starknet-docs/pr-1418/staking/entering-staking/
> Change Argent hardware wallet setup link

- components/Starknet/modules/staking/pages/overview.adoc
Changed the link for the Karnot dashboard on the overview page.
https://starknet-io.github.io/starknet-docs/pr-1420/staking/overview/#important-links
> A link change on overview.adoc

- components/Starknet/modules/staking/pages/entering-staking.adoc
When refering to the Stark token address, I added a disclaimer describing on what chain these addresses are, Sepolia testnet.
https://starknet-io.github.io/starknet-docs/pr-1422/staking/entering-staking/
under the procedure title.
> Added a sepolia disclaimer on entering-staking.adoc

- components/Starknet/modules/tools/pages/devtools/dapp-frameworks.adoc
Fixed a typo in `dapp-frameworks.adoc`.
https://starknet-io.github.io/starknet-docs/pr-1423/tools/devtools/dapp-frameworks/#starknet-scaffold
> Typo fix in dapp-frameworks.adoc

- components/Starknet/modules/starkgate/pages/overview.adoc
I updated the URLs for token address lists (after switching the beta URL to the official URL).
https://starknet-io.github.io/starknet-docs/pr-1433/starkgate/overview/
> fix: updatec URLs for token address lists

- components/Starknet/modules/staking/pages/overview.adoc
Changed the structure of the economical parameter section in the overview.
Added mainnet parameters and corrected the update time from 24 hours to 30 minutes.
https://starknet-io.github.io/starknet-docs/pr-1432/staking/overview/#economic_parameters
> Added mainnet economical param to overview.adoc

- components/Starknet/modules/staking/pages/entering-staking.adoc
In the procedure, I've added the minimum amount of STRK that can be submitted.
https://starknet-io.github.io/starknet-docs/pr-1431/staking/entering-staking/
> Added min stake info to entering-staking.adoc

- components/Starknet/modules/staking/pages/managing-staking-and-delegation-operations.adoc
Commented out obsolete "Changing the Operational Address" in "Managing Staking and Delegation Operations". 
https://starknet-io.github.io/starknet-docs/pr-1437/staking/managing-staking-and-delegation-operations/
> Removed Changing the Operational Address

- components/Starknet/modules/staking/pages/entering-staking.adoc
Added an explanation for `operational_address` in "Becoming a Validator".
https://starknet-io.github.io/starknet-docs/pr-1439/staking/entering-staking/
> operational_address explanation

- components/Starknet/modules/staking/pages/increasing-staking.adoc
Bug fix: Changed the "Note" at the bottom of the procedure. It said that adding stake to a delegator that asked to withdraw will fail. This is not the case.
https://starknet-io.github.io/starknet-docs/pr-1443/staking/increasing-staking/
> Corrected a disclaimer for delegator in increasing-staking.adoc

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/os.adoc
Renamed "The Starknet OS" to "SNOS" in `architecture/os.cairo`.
https://starknet-io.github.io/starknet-docs/pr-1448/architecture-and-concepts/network-architecture/os/
> SN OS -> SNOS rename

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
`nonce` is not at the right place when invoke v3 transaction hash is calculated.
Close: #1459 
https://starknet-io.github.io/starknet-docs/pr-1460/architecture-and-concepts/network-architecture/transactions/
> fix: how invoke transaction v3 hash is calculated

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/contract-storage.adoc
Updated source code language tags in contract-storage.adoc to correctly identify Cairo code blocks. This change improves documentation accuracy and syntax highlighting.
This PR fixes issue (https://github.com/starknet-io/starknet-docs/issues/1463)
Changes made:
- Changed [source,js] to [source,cairo]
- Changed [source,javascript] to [source,cairo]
- No content modifications were made to preserve the original documentation
https://starknet-io.github.io/starknet-docs/pr-1464/architecture-and-concepts/smart-contracts/contract-storage/
Closes #1463
> fix: cairo language tags in contract-storage.adoc

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
Added missing documentation for the Keccak system call to the System Calls section, following the established AsciiDoc format.
Related Issue:-  #1457 
https://starknet-io.github.io/starknet-docs/pr-1461/architecture-and-concepts/smart-contracts/system-calls-cairo1/#keccak
✅Changes made against main branch and PR does not conflict
✅PR title is meaningful
✅Detailed description added 
✅Specific URL(s) added
> docs: add Keccak syscall documentation

- components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc
Replace old references to `<CONTRACT_NAME>.sierra.json` with the newer `<CONTRACT_NAME>.contract_class.json`. This aligns the documentation with the current `scarb build` output and helps first-time users avoid confusion when locating the file. Sierra program is embedded into `*.contract_class.json`
scarb 2.9.2 (5070ff374 2024-12-11)
cairo: 2.9.2 
sierra: 1.6.0
https://starknet-io.github.io/starknet-docs/pr-1470/quick-start/declare-a-smart-contract/
> fix: .sierra.json reference in declare-a-smart-contract.adoc

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/cairo-builtins.adoc
Fix escape of `|` operator in cairo builtins.
Result:
Before:
https://starknet-io.github.io/starknet-docs/pr-1467/architecture-and-concepts/smart-contracts/cairo-builtins/
> fix: cairo-builtins escape `|`

- .htaccess
I'm part of the team maintaining the starknet.io website and a web developer. I have received a report from the company about poorly written redirects on the docs site. This PR includes the addition of slashes to the .htaccess target URLs, where slashes were missing. 
https://starknet-io.github.io/starknet-docs/pr-1530/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1530)
> added missing slashes to .htaccess rules

- components/Starknet/modules/architecture-and-concepts/pages/network-architecture/block-structure.adoc
This PR includes the block header and hash changes that appear in Starknet v0.13.4.
https://starknet-io.github.io/starknet-docs/pr-1518/architecture-and-concepts/network-architecture/block-structure/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1518)
> docs: adapt block hash to Starknet v0.13.4

- js/algolia-index.js
I'm part of the team maintaining the starknet.io website and a web developer. I have received a report from the company about an issue with the way some URLs are being indexed with the ROOT keyword in Algolia. This PR includes the fix to the .replace() function in the Algolia indexing file, generalizing it to replace all URLs preceded by ROOT and not only ROOT/index, which is the current condition for omitting that string.
https://starknet-io.github.io/starknet-docs/pr-1533/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1533)
> generalized ROOT/index replacement for algolia indexing

- components/Starknet/modules/architecture-and-concepts/partials/snippet_transaction_params.adoc
Fix displaying l1 data gas bounds in transactions docs.
Before:
After:
https://starknet-io.github.io/starknet-docs/pr-1534/architecture-and-concepts/network-architecture/transactions/#v3_hash_calculation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1534)
> Fix displaying `l1_data_gas_bounds` in txs docs

- components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
Added missing documentation for the secp256k1 system call to the System Calls section, following the established AsciiDoc format.
Related Issue:- #1204 
https://starknet-io.github.io/starknet-docs/pr-1536/architecture-and-concepts/smart-contracts/system-calls-cairo1/#secp256k1
- ✅ Changes made against main branch and PR does not conflict
- ✅ PR title is meaningful, e.g: `minor typos fix in README`
- ✅ Detailed description added under "Description of the Changes"
- ✅ Specific URL(s) added under "PR Preview URL"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1536)
> docs: added secp256k1 syscall documentation

- components/Starknet/modules/quick-start/pages/troubleshooting.adoc
Documented a Rust issue to the quickstart troubleshooting page.
https://starknet-io.github.io/starknet-docs/pr-1554/quick-start/troubleshooting/#scarb_build_fails_to_run_version_command_for_rust
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1554)
> Quickstart Rust issue

- components/Starknet/modules/quick-start/pages/devnet.adoc
I fixed a couple of typos in the documentation:  
1. The closing bracket for the `id="using_starknet_devnet"` was missing, which has now been corrected.  
2. "Starknet Devent" was mistakenly written instead of the correct "Starknet Devnet."
https://starknet-io.github.io/starknet-docs/pr-1561/quick-start/environment-setup/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1561)
> docs: fix typos in Starknet instance initialization section

- components/Starknet/modules/resources/pages/chain-info.adoc
Fixing a likely typo, based on: https://github.com/starkware-libs/sequencer/blob/main/crates/blockifier/resources/blockifier_versioned_constants_0_14_0.json#L9
https://starknet-io.github.io/starknet-docs/pr-1571/resources/chain-info/#current_limits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1571)
> Fix max bytecode size in chain-info.adoc

- components/Starknet/modules/starkgate/pages/overview.adoc
The current link to "enrolling a token" is broken. Changed it to an original link from the same author.
Also fixed a typo in the previous link text.
https://starknet-io.github.io/starknet-docs/pr-1575/starkgate/overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1575)
> Fix broken link and typo

- components/Starknet/modules/ecosystem/pages/open-rpc-endpoints-sepolia-faucets.adoc
Remove Nethermind from the list of open RPC endpoints
https://starknet-io.github.io/starknet-docs/pr-1611/ecosystem/open-rpc-endpoints-sepolia-faucets/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1611)
> Remove Nethermind from the list of open RPC endpoints

- modules/architecture/pages/staking.adoc
Updated the Epoch length (E) value for Sepolia from 692 (?) to 231 to reflect reality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1679)
> Update Epoch length for Sepolia

- modules/archive/pages/glossary.adoc
Replace broken link to Cairo and Sierra documentation in the glossary. Update from the non-working URL (docs.starknet.io/architecture/smart-contracts/cairo-and-sierra/) to the correct URL in Cairo Book (book.cairo-lang.org/appendix-09-sierra.html) that matches .htaccess redirect rules
https://starknet-io.github.io/starknet-docs/pr-1683/archive/glossary/#sierra
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1683)
> fix: update broken link to Sierra documentation in glossary

- modules/resources/pages/chain-info.adoc
Update mainnet to v0.13.6 and Sepolia to v0.14.0.
https://starknet-io.github.io/starknet-docs/pr-1685/resources/chain-info/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1685)
> Update chain-info.adoc with network versions

- modules/architecture/pages/sharp.adoc
Added the word "instances" to account for a missing word in the text "each two ??? of execution".
Can be another word, but something is missing..
https://starknet-io.github.io/starknet-docs/pr-1689/architecture/sharp/#proof_recursion
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1689)
> Minor typo fix in SHARP page

- modules/archive/pages/cairo-101/arrays.adoc
since we are using type T, I updated the array definition to accept T.
https://github.com/starknet-io/starknet-docs/blob/main/modules/archive/pages/cairo-101/arrays.adoc
- [ ✅ ] Changes made against main branch and PR does not conflict
- [✅] PR title is meaningful, e.g: `minor typos fix in README`
- [ ✅] Detailed description added under "Description of the Changes"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1693)
> Minor fix to cairo-101/arrays

- modules/architecture/pages/blocks.adoc
Minorly clarified state diff commitment in blocks page. 
https://starknet-io.github.io/starknet-docs/pr-1699/architecture/blocks/#state_diff_commitment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1699)
> Minor clarifications to blocks state diff commitment

- modules/architecture/pages/staking.adoc
Clarified a misleading instruction in the staking documentation.
The original text implied that validators must be attesting to blocks **before** staking.
However, this is incorrect - attestation is only possible **after staking is completed and one full epoch has passed**.
**Original line:**
```
a| * You should make sure you are xref:responsibilities[running a full node and attesting to blocks] before staking
```
**Updated line:**
```
a| * You should make sure you are xref:responsibilities[running a fully synchronized node] before staking. Attesting to blocks is only possible starting from the epoch following a successful stake.
```
This change helps avoid confusion for new validators who may attempt attestation too early.
---
https://starknet-io.github.io/starknet-docs/pr-1691/architectu …
> Minor clarification in staking as validators procedures

- modules/architecture/pages/staking.adoc
Clarified the difference between `enter_delegation_pool` and `add_to_delegation_pool` functions in the staking documentation.
* Specified that `enter_delegation_pool` should be used when a user delegates for the **first time** to a pool.
* Explained that `add_to_delegation_pool` is intended for **adding more tokens** after the initial delegation.
These changes aim to eliminate confusion between the two similar-sounding functions and help users avoid mistakes when interacting with the delegation contract.
https://starknet-io.github.io/starknet-docs/pr-1692/architecture/staking/#staking_as_delegators
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1692)
> Minor clarifications in staking as delegators procedures
