starknet-io/starknet-docs

package.json
Reverts starkware-libs/starknet-docs#6
=> Revert "chor: add volta to package.json"

docs/DataAvailabilty/on-chain-data.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/9)
=> docs: data availability 

docs/Blocks/header.md, docs/Fees/fee-mechanism.md, docs/Hashing/hash-functions.md
Fix minor typos in the documentation.
=> fix: fix typos

docs/Events/starknet-events.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/14)
=> docs: events

docs/L1<>L2 Communication/token-bridge.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/23)
=> docs: StarkGate

docs/Blocks/header.md, docs/Blocks/transactions.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/26)
=> docs: chain_id

docs/CLI/commands.md
- [ v ] Changes have been done against dev branch, and PR does not conflict
- [ v ] Docs have been updated
- [ v ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/28)
=> fix: alpha mainnet network parameters

docs/Blocks/header.md, docs/CLI/commands.md, docs/L1<>L2 Communication/token-bridge.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/29)
=> docs: minor 0.8.2 updates

docs/L1<>L2 Communication/token-bridge.md
=> docs: update bridge limitation

docusaurus.config.js
Updating the Discord link in the footer to the same link @ cairo-lang.org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/31)
=> 🐛 Fix: Broken Discord Link

docs/Fees/fee-mechanism.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-docs/37)
=> dos: deployment fee

docs/Blocks/header.md, docs/Blocks/transaction-life-cycle.md, docs/Blocks/transactions.md, docs/CLI/commands.md, docs/Contracts/contract-address.md, docs/Contracts/contract-classes.md, docs/Contracts/contract-hash.md, docs/Data Availabilty/on-chain-data.md, docs/Events/starknet-events.md, docs/Fees/fee-mechanism.md, docs/L1<>L2 Communication/token-bridge.md, docs/State/starknet-state.md
=> fix: relative urls throughout the docs

docs/L1<>L2 Communication/messaging-mechanism.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/41)
=> docs: fix typo on "relvant"

docs/CLI/commands.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/43)
=> docs: fix link for openzeppelin account.cairo

docs/Blocks/transaction-life-cycle.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/47)
=> docs: transaction life cycle descrpition fix

docs/Blocks/transactions.md
=> docs: fix max_fee type

docs/CLI/commands.md
Bug fix: This fixes the link to the OpenZeppelin contract.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/51)
=> Docs: Fix link to OpenZeppelin contract.

docs/Data Availabilty/on-chain-data.md, docs/State/starknet-state.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)
=> docs: nonce in on chain data and the state definition

docs/Blocks/transactions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)
=> docs: update transaction hash computation

components/StarkNet/modules/develop/pages/CLI/commands.adoc, ui/supplemental_ui/css/supplemental.css
- Moved and rewrote tips on setting network variable and gateways
- Fixed broken link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/64)
=> Fix command.adoc bugs

components/StarkNet/modules/ROOT/pages/Ecosystem/con_block_explorers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/68)
=> Added Viewblock to Block explorers topic.

ui/supplemental_ui/partials/header-content.hbs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/69)
=> Fix: Updated Discord link

.github/workflows/tag.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/70)
=> Reverted node-version to 14.

.github/workflows/pull_request.yml, .github/workflows/tag.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/71)
=> Debugging workflows

.github/workflows/push.yml, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/72)
=> Restored code previously removed from package.json to see if it successfully generates a Pre-release tag.

.github/workflows/tag.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/74)
=> Increased verson of node to 16 in tag.yml.

CHANGELOG.md, package-lock.json, package.json, playbook.yml
Reverts starknet-community-libs/starknet-docs#76
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/77)
=> Revert "Feat: Enable google analytics"

playbook.yml
Added Google analytics ID to playbook.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/78)
=> Added google_analytics ID.

.github/PULL_REQUEST_TEMPLATE.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/84)
=> Added `docs` back into PR template guidelines.

CHANGELOG.md, components/StarkNet/modules/ROOT/nav.adoc, components/StarkNet/modules/ROOT/pages/Ecosystem/ref_block_explorers.adoc, package-lock.json, package.json
Changed name of file from `con_block_explorers.adoc` to `ref_block_explorers.adoc` because topic is a reference topic. Added italics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/93)
=> fix: Steve/test deploy

README.adoc
Readme updates:
- added TOC
- updated installation and build instructions
- added Git-related info
- added release procedure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/82)
=> [doc]: README--Updated contribution guidelines

.github/workflows/tag.yml
Changing deploy flow to deploy to the Production website.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/94)
=> chore:Changed deploy workflow from STAGING to PROD

CHANGELOG.md, package-lock.json, package.json
Merge updates from master to dev
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/99)
=> chore(release): 0.1.5

components/StarkNet/modules/develop/nav.adoc, components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc, components/StarkNet/modules/develop/pages/Hashing/hash-functions.adoc, components/StarkNet/modules/develop/pages/State/starknet-state.adoc
Fixed a few typos and misphrasing.
https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/Contracts/contract-hash/
https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/Hashing/hash-functions/
https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/State/starknet-state/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)
=> fix: Fixed a few typos and Contract Hash -> Class Hash

components/StarkNet/modules/develop/nav.adoc
TOC: Added new section: Network architecture, includes content currently on docs.starknet.io
https://starknet-community-libs.github.io/starknet-docs/pr-86/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)
=> docs: Add Network architecture section

.github/PULL_REQUEST_TEMPLATE.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/96)
=> chore: Added a section for the PR preview to the PR template.

components/StarkNet/modules/develop/pages/Fees/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/105)
=> James: Update - Modify fee mechanism weighting on fee page to match cairo-v0.10.2

components/StarkNet/antora.yml, components/StarkNet/modules/hello_starknet/nav.adoc, components/StarkNet/modules/hello_starknet/pages/account_setup.adoc, components/StarkNet/modules/hello_starknet/pages/amm.adoc, components/StarkNet/modules/hello_starknet/pages/calling_contracts.adoc, components/StarkNet/modules/hello_starknet/pages/cli.adoc, components/StarkNet/modules/hello_starknet/pages/constructors.adoc, components/StarkNet/modules/hello_starknet/pages/default_entrypoint.adoc, components/StarkNet/modules/hello_starknet/pages/deploying_from_contracts.adoc, components/StarkNet/modules/hello_starknet/pages/events.adoc, components/StarkNet/modules/hello_starknet/pages/index.adoc, components/StarkNet/modules/hello_starknet/pages/intro.adoc, components/StarkNet/modules/hello_starknet/pages/l1l2.adoc, components/StarkNet/modules/hello_starknet/pages/more_features.adoc, components/StarkNet/modules/hello_starknet/pages/signature_verification.adoc, components/StarkNet/modules/hello_starknet/pages/unit_tests.adoc, components/StarkNet/modules/hello_starknet/pages/user_auth.adoc
Converting Hello StarkNet from RST to AsciiDoc.
https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/hello_starknet/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)
=> chore: Converting Hello StarkNet from RST to AsciiDoc

components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc
Added link to goerli2.json (json with token addresses)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/108)
=> Added link to goerli2.json

CHANGELOG.md, package-lock.json, package.json
Rebase dev to master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/118)
=> Rebase dev to master

CHANGELOG.md, package-lock.json, package.json
Redeploying alphabetization after deployment fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/120)
=> Redeploying alphabetization

components/StarkNet/modules/develop/nav.adoc, components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc
Adding system calls to section on contract classes.
https://starknet-io.github.io/starknet-docs/pr-79/documentation/develop/Contracts/system-calls/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/79)
=> [doc] Adding system calls

README.adoc
Switched back to using merge vs rebase for dev -> master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/124)
=> james: Update readme to reflect updated deployment process

components/StarkNet/modules/architecture_and_concepts/nav.adoc
* Added system calls back into the new menu structure
Add missing system calls page back in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/139)
=> James/main nav restructure hello starknet (#132)

components/StarkNet/modules/ROOT/pages/version_notes.adoc
Update versions page to reflect 0.10.3 on mainnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/157)
=> Update versions page to reflect 0.10.3 on mainnet

components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc
https://starknet-io.github.io/starknet-docs/pr-174/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/174)
=> Correct formula under state commitment

CHANGELOG.md, components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/193)
=> Update direction of messaging in deprecated

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/207)
=> Update 0.11.0 page: more info about replace class and minor fixes

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
Add sections to pathfinder versions section
https://starknet-io.github.io/starknet-docs/pr-206/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/206)
=> Add pathfinder versions to version section

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
Add pathfinder section to version notes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/223)
=> Pathfinder versions

components/StarkNet/modules/starknet_versions/nav.adoc
Hide pathfinder versions from live version
https://starknet-io.github.io/starknet-docs/pr-225/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/225)
=> Hide path finder from side nav

components/StarkNet/modules/architecture_and_concepts/pages/Blocks/header.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-hash.adoc, components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc, components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
Updates to hash and transaction commitment from @anshulforyou
Thank you!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/226)
=> Merge in changes from anshulforyou

CHANGELOG.md, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/232)
=> Deploy syntax highlighting

ui/supplemental_ui/partials/header-content.hbs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/237)
=> Update header to match redesign

ui/supplemental_ui/partials/header-content.hbs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/238)
=> Update nav 

CHANGELOG.md, components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc, components/StarkNet/modules/getting_started/pages/unit_tests.adoc, components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc, components/StarkNet/modules/tools/pages/CLI/starknet-compiler-options.adoc, package-lock.json, package.json, ui/supplemental_ui/partials/header-content.hbs
Fix a few instances of incorrect case of StarkNet (starknet)
https://starknet-io.github.io/starknet-docs/pr-239/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/239)
=> Correct casing on starknet

components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc
=> Update links on removed features page

components/StarkNet/modules/architecture_and_concepts/pages/Blocks/header.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-hash.adoc, components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/247)
=> Merge latest to master

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
Add page for StarkNet limits and triggers
https://starknet-io.github.io/starknet-docs/pr-236/documentation/starknet_versions/limits_and_triggers/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/236)
=> Add limits and triggers page

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
* Update limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/250)
=> Add limits and triggers page (#236)

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/251)
=> Put pathfinder versions live

components/StarkNet/modules/starknet_versions/nav.adoc, components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/252)
=> Stark net limits and triggers

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls.adoc
Fix broken link to Hello Starknet
https://starknet-io.github.io/starknet-docs/pr-267/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/267)
=> Fix broken link to Hello Starknet

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls.adoc, components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/268)
=> Fix missing hello starknet link

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/275)
=> v0.11.0 - upcoming version changelog

components/StarkNet/modules/useful_info/nav.adoc, components/StarkNet/modules/useful_info/pages/index.adoc
Rename useful info to important addresses
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/290)
=> Rename useful info to important addresses

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls.adoc
v0.11.0 Update system calls
https://starknet-io.github.io/starknet-docs/pr-283/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/283)
=> v0.11.0 Update system calls

components/StarkNet/modules/getting_started/nav.adoc, components/StarkNet/modules/getting_started/pages/setting_up_the_environment.adoc, components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
Migrate this page: https://starknet.io/docs/quickstart.html#quickstart
To starknet docs site
https://starknet-io.github.io/starknet-docs/pr-297/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/297)
=> Setting up the environment migrated

components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc
v0.11.0 Update removed and depreceated feature page to reflect 0.11.0
https://starknet-io.github.io/starknet-docs/pr-284/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/284)
=> v0.11.0 Update removed and depreceated feature page to reflect 0.11.0

components/StarkNet/modules/getting_started/pages/account_setup.adoc, components/StarkNet/modules/getting_started/pages/intro.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/301)
=> Fix broken links

ui/src/partials/footer-scripts.hbs, ui/src/partials/head-scripts.hbs, ui/src/partials/head-styles.hbs, ui/supplemental_ui/partials/footer-scripts.hbs, ui/supplemental_ui/partials/head-styles.hbs
add `?new` suffix to css and js imports in html to force refetching from browsers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/319)
=> fix(ui): force browsers to refetch css and js assets

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-storage.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/327)
=> Initial commit with tab placeholders

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Hashing/hash-functions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/331)
=> refactor class hash description

components/StarkNet/modules/architecture_and_concepts/pages/Hashing/hash-functions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/332)
=> fix poseidon notation

components/StarkNet/modules/architecture_and_concepts/pages/Hashing/hash-functions.adoc
Quick fix for typo on number of hash functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/335)
=> Hotfix: Fix error

components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
Update Goerli block gas limit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/345)
=> Update Goerli block gas limit

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
Update version notes to reflect rescheduling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/347)
=> Update version notes to reflect rescheduling

.github/workflows/pull_request.yml, components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
Fix deploy script
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/349)
=> Fix deploy script

components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
Add missing deploy account transaction from intro paragraph
https://starknet-io.github.io/starknet-docs/pr-351/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/351)
=> Add missing deploy account transaction from intro paragraph

components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc
State commitment: v0.11.0 updates 
https://starknet-io.github.io/starknet-docs/pr-353/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/353)
=> state commitment: v0.11.0 updates

components/StarkNet/modules/architecture_and_concepts/nav.adoc, components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc
Revert state and Sierra changes until reviewed for 0.11.0 (#358)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/358)
=> Revert state and Sierra changes until reviewed for 0.11.0

components/StarkNet/modules/architecture_and_concepts/nav.adoc, components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/359)
=> Revert state and Sierra changes until reviewed for 0.11.0 (#358)

.github/workflows/pull_request.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/362)
=> Switch user token for github token

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-abi.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/366)
=> Add tabs to abi

components/StarkNet/modules/architecture_and_concepts/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/371)
=> Rearrange menu

components/StarkNet/modules/architecture_and_concepts/nav.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-abi.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-storage.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Events/starknet-events.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc, components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/372)
=> Add Cairo 1 code examples

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/373)
=> cairo 1.0 syscalls

components/StarkNet/modules/architecture_and_concepts/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/374)
=> Remove additional concepts section

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
=> Update to make publishable

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
=> Upcoming versions

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc, ui/src/css/extensions/custom-dark.css
=> Tabs dark mode

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls.adoc, components/StarkNet/modules/end_of_life_and_deprecated_features/pages/index.adoc
=> Fix build errors

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/cairo-1-and-sierra.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/381)
=> Small fixes to cairo-1-and-sierra

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/contract-abi.adoc
=> Fix broken link

components/StarkNet/modules/architecture_and_concepts/nav.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls-cairo0.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls-cairo1.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/390)
=> Split syscalls into cairo0/cairo1

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/395)
=> Add some 0.11.0 detail back into versions page (previously approved)

components/StarkNet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/397)
=> update state commitment and fix broken links

components/StarkNet/antora.yml
Hide getting started for Cairo 0 until Cairo 1.0 version is ready
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/398)
=> Hide getting started for Cairo 0 until Cairo 1.0 version is ready

components/StarkNet/antora.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/399)
=> Hide getting started for Cairo 0 until Cairo 1.0 version is ready (#398)

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
Update version notes to reflect mainnet v0.11.0 update
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/405)
=> Update version notes to reflect mainnet v0.11.0 update

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
Update the mainnet version to reflect the current deployed version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/402)
=> docs (versions) : update mainnet version to v0.11.0

components/StarkNet/modules/getting_started/pages/setting_up_the_environment.adoc
It's a minor fix, but participating to keep consistent formatting along the documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/400)
=> docs (getting_started): minor code snippet indentation fix

components/StarkNet/antora.yml, components/StarkNet/modules/getting_started/pages/setting_up_the_environment.adoc, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/406)
=> Latest revision to docs to include 0.11.0 update

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
First draft of upcoming 0.12.0 and 0.13.0 features
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/409)
=> First draft of upcoming versions update

components/StarkNet/modules/starknet_versions/pages/upcoming_versions.adoc
Add extra content around upcoming version 0.12.0 of Starknet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/418)
=> Add extra detail to upcoming version 0.12.0

components/StarkNet/modules/starknet_versions/pages/juno_versions.adoc
Add recent Juno versions.
file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/425)
=> docs: add recent Juno versions

components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
This PR updates the pathfinder version docs to the latest version v0.5.3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/429)
=> docs: update pathfinder versions

components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
Previous values have been cut by a factor of 5
https://starknet-io.github.io/starknet-docs/pr-430/documentation/architecture_and_concepts/Fees/fee-mechanism/#computation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/430)
=> Update the fee mechanism page to reflect the most current gas fees

components/StarkNet/modules/starknet_versions/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/435)
=> docs: Add max transaction size to limits & triggers

components/StarkNet/modules/starknet_versions/pages/pathfinder_versions.adoc
Adds pathfinder v0.5.4 release notes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/453)
=> docs: pathfinder v0.5.4 release notes

components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/455)
=> Update to latest bridge limits

CHANGELOG.md, components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc, package-lock.json, package.json
Environment setup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/476)
=> Environment setup

CHANGELOG.md, package-lock.json, package.json
Environment setup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/477)
=> Environment setup (#476)

CHANGELOG.md, components/StarkNet/modules/getting_started/nav.adoc, components/StarkNet/modules/getting_started/pages/account_setup.adoc, package-lock.json, package.json
Account setup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/478)
=> Account setup

playbook.yml
Update GA tracking code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/485)
=> Update GA tracking code

components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc
Update wording on validate in AA section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/487)
=> Update wording on validate in AA section

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
https://starknet-io.github.io/starknet-docs/pr-474/documentation/starknet_versions/version_notes/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/474)
=> Add compiler support version to versions table

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
=> Add compiler support version to versions table (#474)

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
* Add compiler support version to versions table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/505)
=> James/add compiler version to versions table (#501)

components/StarkNet/modules/getting_started/pages/environment_setup.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/507)
=> Getting Started - Fix links

components/StarkNet/modules/getting_started/pages/environment_setup.adoc
Getting Started - Fix links (#507)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/508)
=> Fix links (#507)

components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
Prep for 0.11.2 Testnets
https://starknet-io.github.io/starknet-docs/pr-503/documentation/starknet_versions/version_notes/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/503)
=> 0.11.2 Mainnet

components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc
https://starknet-io.github.io/starknet-docs/pr-492/documentation/architecture_and_concepts/L1-L2_Communication/token-bridge/#starkgate_alpha_limitations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/492)
=> Remove single txn limit as is no longer needed

components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc, components/StarkNet/modules/getting_started/pages/environment_setup.adoc, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/511)
=> Remove txn limit for bridge in table (no longer needed)

.github/workflows/push.yml
Explicitly change name of deploy user
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/513)
=> Explicitly change name of deploy user

.github/workflows/push.yml, components/StarkNet/modules/starknet_versions/pages/version_notes.adoc
Update mailing list link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/517)
=> Update mailing list link

.github/workflows/push.yml
=> Revert gitflow

components/StarkNet/modules/architecture_and_concepts/pages/Data_Availability/on-chain-data.adoc
Minor fixes in "Data availability".
https://starknet-io.github.io/starknet-docs/pr-534/documentation/architecture_and_concepts/Data_Availability/on-chain-data/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/534)
=> fix: minor fixes in "Data availability"

components/StarkNet/modules/architecture_and_concepts/pages/Events/starknet-events.adoc
Minor fixes in "Events".
https://starknet-io.github.io/starknet-docs/pr-533/documentation/architecture_and_concepts/Events/starknet-events/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/533)
=> fix: minor fixes in "Events"

components/StarkNet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc
Minor fixes in "Strakgate bridge".
https://starknet-io.github.io/starknet-docs/pr-531/documentation/architecture_and_concepts/L1-L2_Communication/token-bridge/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/531)
=> fix: minor fixes in "Strakgate bridge"

components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
Minor fixes in "Gas and transaction fees".
https://starknet-io.github.io/starknet-docs/pr-529/documentation/architecture_and_concepts/Fees/fee-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/529)
=> fix: minor fixes in "Gas and transaction fees"

components/StarkNet/modules/tools/nav.adoc, components/StarkNet/modules/tools/pages/api_rpc.adoc
Add a table of API and Full node providers
https://starknet-io.github.io/starknet-docs/pr-541/documentation/tools/api_rpc/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/541)
=> Add Bware labs

components/StarkNet/modules/tools/nav.adoc, components/StarkNet/modules/tools/pages/api_rpc.adoc
* Update api_rpc.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/542)
=> Add list of Full-nodes and API providers

components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc, components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/544)
=> Update wording on AA Deploying accounts (#540)

CHANGELOG.md, components/StarkNet/modules/tools/nav.adoc, package-lock.json, package.json
* chore(release): 0.1.158
* Update wording on AA Deploying accounts (#540) (#544)
* chore(release): 0.1.159
* Update nav.adoc
---------
Co-authored-by: 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 <>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/546)
=> rJames/hotfix menu caps (#545)

CHANGELOG.md, components/StarkNet/modules/tools/nav.adoc, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/549)
=> Fix menu casing

CHANGELOG.md, components/StarkNet/modules/architecture_and_concepts/pages/State/starknet-state.adoc, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/560)
=> Starknet state improvements

CHANGELOG.md, components/StarkNet/modules/architecture_and_concepts/pages/Contracts/system-calls-cairo0.adoc, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/570)
=> System calls Cairo 0 updates

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc, package-lock.json, package.json
Add Cairo contract syntax updates for Starknet to 0.12.0 upcoming versions page.
https://starknet-io.github.io/starknet-docs/pr-569/documentation/starknet_versions/upcoming_versions/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/569)
=> Add smart contract syntax improvements to 0.12.0 upcoming versions

components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/580)
=> change emit example in the syntax migration page

.github/workflows/algolia-indexing.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/575)
=> Trigger algolia indexing on dev & master branch changes

.github/workflows/algolia-indexing.yml, components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc
Algolia search fix and contract migration syntax simplification
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/581)
=> Algolia search fix and contract migration syntax simplification

components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/cairo-1-and-sierra.adoc, components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/582)
=> Move Cairo pages to correct namespace

.github/workflows/algolia-indexing.yml, components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc, components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/cairo-1-and-sierra.adoc, components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc
Fix issue relating to namespaces
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/583)
=> Fix issue relating to namespaces

.github/workflows/algolia-indexing.yml, js/algolia-index.js
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/589)
=> Trigger algolia indexing only when there is a change in adoc files

components/Starknet/modules/architecture_and_concepts/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/599)
=> Update nav.adoc (#598)

components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/cairo-1-and-sierra.adoc, components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc, components/Starknet/modules/useful_info/pages/index.adoc
=> Sierra, syscall and deprecated feature updates

components/Starknet/modules/tools/pages/api_rpc.adoc
Minor fixes in "Starknet full-nodes and API providers".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/600)
=> fix: minor fixes in "Starknet full-nodes and API providers"

components/Starknet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/cairo-1-and-sierra.adoc, components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc, components/Starknet/modules/useful_info/pages/index.adoc
=> Switch order of node providers and api providers

.github/workflows/algolia-indexing.yml, js/algolia-index.js
- Improve title extraction logic
- Remove `ROOT/index` and `index` from urls
- Trigger algolia indexing when script is updated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/609)
=> Fix title extraction && remove index from url

components/Starknet/modules/useful_info/pages/index.adoc
Update Goerli verifier address
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/611)
=> Update Goerli verifier address

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
Modify range for get_block_hash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/615)
=> Maker changes to block_hash for upcoming 0.12.0

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/616)
=> Maker changes to block_hash for upcoming 0.12.0 (#615)

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/623)
=> Update testnet versions for 0.12.0

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
* Update testnet versions for 0.12.0
* Update version_notes.adoc
* Add upcoming version section for 0.12.0
* Feedback actioned
* Update version_notes.adoc
=> Update testnet versions for 0.12.0 (#623)

components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc
* Move limits table to top of page based on analytics insights
* Change structure and correct caps
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/627)
=> Move limits table to top of page based on analytics insights (#612)

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/630)
=> Add HTTP error codes (#628)

components/Starknet/modules/architecture_and_concepts/pages/Contracts/system-calls-cairo1.adoc, components/Starknet/modules/architecture_and_concepts/pages/State/starknet-state.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, package-lock.json, package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/636)
=> James/versions 0.12.0

components/Starknet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
Bugfix for a `data availability` link in the fees section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/639)
=> fix:  data availability href fix

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/token-bridge.adoc, components/Starknet/modules/starknet_versions/pages/limits_and_triggers.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc, components/Starknet/modules/tools/pages/ref_block_explorers.adoc, components/Starknet/modules/useful_info/pages/audit.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/640)
=> Add [%autowidth.stretch] to tables

components/Starknet/modules/getting_started/pages/environment_setup.adoc
=> Revert env setup

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/645)
=> Fix internal page links and pending status

components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc
=> feat: add pathfinder versions (#651)

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
* Add Keccak to Upcoming versions
* Update based on feedback
=> Add Keccak builtins to Upcoming versions (#634)

components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc
Adds the latest pathfinder v0.6.6 changelog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/657)
=> docs: pathfinder v0.6.6

components/Starknet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Contracts/contract-address.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/658)
=> Update contract address page

components/Starknet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Contracts/contract-address.adoc, components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/661)
=> Contract address page updates

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Contracts/contract-address.adoc, components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/662)
=> Transaction version update

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update date for 0.12.0

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update version_notes.adoc (#666)

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/670)
=> Remove pending status

components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
Add recent Juno versions.
`file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/682)
=> docs: add Juno v0.4.1 details

components/Starknet/modules/architecture_and_concepts/pages/Contracts/contract-abi.adoc
Removed redundant word.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/691)
=> fix: typo on Contracts ABI page

components/Starknet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc
Changed link to Cairo 0 interface for Account Contract to SNIP6 as it uses a Cairo 1 trait
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/683)
=> docs: Update approach.adoc to point to Cairo 1 trait for AA

components/Starknet/modules/end_of_life_and_deprecated_features/pages/index.adoc, components/Starknet/modules/getting_started/pages/environment_setup.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/CLI/commands.adoc, components/Starknet/modules/tools/pages/CLI/starkli.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/705)
=> Starkli addition, table width and Compiler version updates

components/Starknet/modules/architecture_and_concepts/pages/Contracts/contract-abi.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/699)
=> docs: Cairo v2 contract ABI

components/Starknet/modules/tools/pages/CLI/starkli.adoc
Tech writing edits
Implemented style and-writing guidelines in Starkli CLI topic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/706)
=> Fix: Edits to starkli.adoc

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/707)
=> Update transactions page

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
=> Update transactions.adoc (#707)

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/710)
=> Should have been removed already

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/711)
=> Remove pending block note, no longer needed

components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/712)
=> Update cairo example `send_message_to_l1`

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc
=> Update communication code snippet to Cairo 1

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc
Swap usage of & for and
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/701)
=> Swap ampersand for and

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc
=> Ampersand fix

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc
=> 0.12.1 testnet release

components/Starknet/modules/architecture_and_concepts/pages/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/L1-L2_Communication/messaging-mechanism.adoc, components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/api_rpc.adoc
=> Correct grammatical error

components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
Add recent Juno version.
`file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/722)
=> docs: add Juno v0.5.0 details

components/Starknet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
Add Keccak cost to weighting table on fee mechanism page.
https://starknet-io.github.io/starknet-docs/pr-717/documentation/architecture_and_concepts/Fees/fee-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/717)
=> Add Keccak to table, also switch format and add clearer striped styling

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Cryptography/p-value.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Data_Availability/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Fees/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/L1-L2_Communication/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/Events/starknet-events.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-syntax.adoc, components/Starknet/modules/cli/pages/starknet-compiler-options.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/tools/pages/audit.adoc, components/Starknet/modules/tools/pages/ref_block_explorers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/743)
=> Hotfix for menu title vs nav consistency

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Cryptography/p-value.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Data_Availability/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Fees/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/L1-L2_Communication/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/Events/starknet-events.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-syntax.adoc, components/Starknet/modules/cli/pages/starknet-compiler-options.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/tools/pages/audit.adoc, components/Starknet/modules/tools/pages/ref_block_explorers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/744)
=> Fix title vs nav consistency

contributing_to_docs/starknet_docs_style_guide.adoc
Minor edits to definition for drop-down in style guide
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/749)
=> fix: Minor edits to definition for drop-down in style guide

components/Starknet/antora.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/753)
=> Hide glossary pending technical review

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/757)
=> 0.12.2 to testnet 2

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/761)
=> Remove Cairo 0 class hash

components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
Add recent Juno version.
`file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/765)
=> docs: add Juno v0.6.0 details

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transactions.adoc
=> fix order of hash calculation (#767)

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
Add block time to limits and triggers page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/770)
=> Add block time to limits and triggers

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
* Add block time to limits and triggers
* Remove max
=> Add block time to limits and triggers (#770)

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/State/starknet-state.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/726)
=> docs: Add special address section

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/State/starknet-state.adoc, components/Starknet/modules/tools/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/772)
=> Special addresses section added to state

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/State/starknet-state.adoc, components/Starknet/modules/tools/pages/limits_and_triggers.adoc
=> Update validation to include the validation step on the sequencer

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/776)
=> Update v0, v1 and v2 code examples (#775)

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/774)
=> Add warning for lack of error catch on call_contract syscall

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Blocks/transactions.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/777)
=> Add warning for call contract error catching

components/Starknet/modules/quick_start/pages/environment_setup.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/781)
=> Environment setup using StarkLi and Scarb

components/Starknet/modules/quick_start/pages/environment_setup.adoc
* Environment setup using StarkLi and Scarb
* Update environment_setup.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/782)
=> Environment setup using StarkLi and Scarb (#781)

components/Starknet/modules/starknet_versions/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/784)
=> Search fix - silent deploy

components/Starknet/modules/starknet_versions/nav.adoc
=> Update nav.adoc (#784)

components/Starknet/antora.yml, components/Starknet/modules/ROOT/nav_glossary.adoc, components/Starknet/modules/ROOT/pages/glossary.adoc, components/Starknet/modules/starknet_versions/nav.adoc
=> Remove glossary from search index

components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/791)
=> Update to include max steps adjustment

components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/limits_and_triggers.adoc
=> Update to include max steps adjustment (#791)

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc
Update Starkgate bridge values
https://starknet-io.github.io/starknet-docs/pr-796/documentation/architecture_and_concepts/Network_Architecture/token-bridge/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/796)
=> Update bridge values

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update bridge values and clarify changelog

components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/compile_and_deploy.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc
* Environment setup using StarkLi and Scarb
* Update environment_setup.adoc
* Initial commit of updated Starkli and scarb quick start
* Split the setup in to logical sections
* Version 1 for deployment
* Menu updates
* Complete guide version 1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/798)
=> James/setup (#783)

components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/800)
=> Update all instances of on-chain to onchain (#799)

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc
Fix case of Starkgate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/795)
=> fix: Update token-bridge.adoc: Starkgate -> StarkGate

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update Starkgate to StarkGate

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/cairo-and-sierra.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update nonce description

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/cairo-and-sierra.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/api-services.adoc
=> Add Chainbase to API providers page

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/806)
=> Update feeder gateway dates

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
=> Update upcoming_versions.adoc (#806)

contributing_to_docs/starknet_docs_style_guide.adoc
=> Update contribution guidelines for tx

contributing_to_docs/starknet_docs_style_guide.adoc
=> Update starknet_docs_style_guide.adoc (#808)

contributing_to_docs/setting_up_environment.adoc, contributing_to_docs/starknet_docs_style_guide.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/810)
=> Add git related info - merging to dev

contributing_to_docs/setting_up_environment.adoc, contributing_to_docs/starknet_docs_style_guide.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/811)
=> Git related info - merging to dev

components/Starknet/modules/quick_start/pages/setting_up_a_smart_wallet.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/813)
=> Update account fetch command - quick start

components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/815)
=> Update api services

components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/816)
=> Update api-services.adoc (#815)

components/Starknet/modules/quick_start/pages/account_setup.adoc, components/Starknet/modules/tools/pages/api-services.adoc
=> Update commands to fix errors

components/Starknet/modules/quick_start/pages/compile_and_deploy.adoc
=> Update compile_and_deploy.adoc (#821)

components/Starknet/modules/quick_start/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/826)
=> Update nav.adoc (#825)

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
* fix broken links
* Update fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/834)
=> Fix broken links (#832)

components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/833)
=> Add Nethermind RPC

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/836)
=> RPC Nethermind addition

components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/deploy_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/838)
=> Reformat and simplify structure of quick start

components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/deploy_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc
=> Reformat and simplify structure of quick start (#838)

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/844)
=> Update feeder gateway deprecation dates on the Starknet docs

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/simplified_transaction_flow.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/header.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc, components/Starknet/modules/starknet_versions/pages/deprecated.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/848)
=> Initial feedback and fix all asciidoc errors

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/simplified_transaction_flow.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/header.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc, components/Starknet/modules/starknet_versions/pages/deprecated.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/849)
=> Initial feedback and fix all asciidoc errors (#848)

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/simplified_transaction_flow.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/header.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/class-hash.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/quick_start/nav.adoc, components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc, components/Starknet/modules/quick_start/pages/environment_setup.adoc, components/Starknet/modules/quick_start/pages/interact_with_a_smart_contract.adoc, components/Starknet/modules/starknet_versions/pages/deprecated.adoc, components/Starknet/modules/tools/pages/api-services.adoc
=> Update Nethermind RPC url

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc
Minor edits, clarification and grammar.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/859)
=> fix: StarkGate Bridge minor edits

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/introduction.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc, contributing_to_docs/doc_guidelines.adoc, contributing_to_docs/starknet_docs_style_guide.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/863)
=> Correct typo and merge latest reviews

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/tools/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/868)
=> Rename menu items and simplify

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/tools/nav.adoc
=> Rename menu items and simplify (#868)

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/tools/nav.adoc, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/871)
=> Force deploy

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-syntax.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/874)
=> Contract migration guide changes

components/Starknet/modules/quick_start/pages/set_up_an_account.adoc
A few minor edits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/877)
=> Minor clarifications in set_up_an_account.adoc

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/881)
=> Add compiler version supported range

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/cli/pages/starknet-compiler-options.adoc, components/Starknet/modules/tools/nav.adoc, package-lock.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/880)
=> Reword Cairo 0 tools menu and headers

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/cli/pages/starknet-compiler-options.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/nav.adoc, package-lock.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/884)
=> Cairo 0 menu updates and version table compiler version

components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
Add v0.7.0 Juno version.
file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/887)
=> docs: add Juno v0.7.0 details

contributing_to_docs/starknet_docs_style_guide.adoc
Added onchain and offchain terms to style guide to align with industry usage trends.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/894)
=> chore: Added onchain and offchain terms to style guide.

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc
*Contract classes*
Minor clarifications; moved links to Additonal resources section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/895)
=> fix: Updates to *Contract classes*

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
Add new row for max validate steps in limits and triggers, measured in Cairo steps.
https://starknet-io.github.io/starknet-docs/pr-900/documentation/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/900)
=> Add new row for max validate steps in limits and triggers

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-address.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/911)
=> Update the link to the Cairo contract code in address section

components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/916)
=> Update upcoming_versions.adoc with Starknet v0.12.3 mainnet upgrade

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/925)
=> fix: Minor edits to clean up mention of chain ids.

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc
Added a link to StarkGate from the page about StarkGate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/926)
=> docs: Add a link to StarkGate

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/928)
=> Add in changes from #731 - as PR contained unwanted changes

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
Update mailing list link to the new one.
https://starknet-io.github.io/starknet-docs/pr-934/documentation/starknet_versions/version_notes/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/934)
=> Update version_notes.adoc with link to new mailing list

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/940)
=> Cairo versions: add 2.3.1 to mainnet

components/Starknet/modules/architecture_and_concepts/pages/Accounts/simplified_transaction_flow.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/944)
=> fix: Minor edits in simplified_transaction_flow.adoc

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/947)
=> docs: Update testnet version to 0.12.3

components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/starknet_versions/nav.adoc, components/Starknet/modules/starknet_versions/pages/deprecated.adoc, components/Starknet/modules/starknet_versions/pages/upcoming_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, contributing_to_docs/starknet_docs_style_guide.adoc
Updating release note information for version 0.12.3.
- [Starknet release notes](https://starknet-io.github.io/starknet-docs/pr-948/documentation/starknet_versions/version_notes/)
- [Deprecated, unsupported, and removed features](https://starknet-io.github.io/starknet-docs/pr-948/documentation/starknet_versions/deprecated/)
- [Upcoming Starknet versions](https://starknet-io.github.io/starknet-docs/pr-948/documentation/starknet_versions/upcoming_versions/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/948)
=> docs: Release notes for 0.12.3

README.adoc
Fixed typo in https://github.com/starknet-io/starknet-docs#releasing-starknet-docs-on-github, described in the issue #931 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/950)
=> fix: typo in docs releasing-starknet-docs-on-github (#931)

README.adoc
Merge dev to master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/951)
=> fix: typo in docs releasing-starknet-docs-on-github (#931) (#950)

CHANGELOG.md, package-lock.json, package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/952)
=> chore(release): 0.1.353

components/Starknet/modules/tools/pages/api-services.adoc
Add a link the JSON RPC.
[Full nodes and API services](https://starknet-io.github.io/starknet-docs/pr-957/documentation/tools/api-services/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/957)
=> docs: Add a link the JSON RPC.

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/important_addresses.adoc
Add addresses and Chain ID for Sepolia.
[Important addresses](https://starknet-io.github.io/starknet-docs/pr-956/documentation/tools/important_addresses/)
[Chain IDs in Transaction types](https://starknet-io.github.io/starknet-docs/pr-956/documentation/architecture_and_concepts/Network_Architecture/transactions/#chain-id)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/956)
=> docs: Add addresses and Chain ID for Sepolia.

components/Starknet/modules/architecture_and_concepts/pages/Accounts/deploying_new_accounts.adoc
This PR is to test the recent changes to the workflow in #961.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/962)
=> docs: Tiny edit.

contributing_to_docs/setting_up_environment.adoc
Contribution guidelines: Updated reviewers, and that you need to merge to master.
No relevant preview. Only the contribution guidelines were changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/965)
=> chore: Contribution guidelines: Updated reviewers, and that you need to merge to master.

README.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/966)
=> chore: Updated release process in README.adoc

components/Starknet/modules/architecture_and_concepts/pages/Accounts/deploying_new_accounts.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/967)
=> fix: Minor edits.

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/971)
=> fix: Clarifications in Starknet state

components/Starknet/modules/tools/pages/important_addresses.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/968)
=> Update important_addresses.adoc with bridged tokens to Sepolia testnet

components/Starknet/modules/architecture_and_concepts/nav.adoc
Change toc entry to _Migrating a contract from Cairo 0 to Cairo_
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/974)
=> fix: Change toc entry to _Migrating a contract from Cairo 0 to Cairo_

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/972)
=> fix: Rewrote Contract tree hash

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-storage.adoc
Applied new cairo syntax for Contract storage (maybe someone missed these places)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/960)
=> fix: apply new cairo syntax for Contract storage (Previously #959)

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-storage.adoc
Same thing as #960, which was accidentally merged to dev instead of master.
Fixes issue #883.
Applied new cairo syntax for Contract storage (maybe someone missed these places)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/975)
=> fix: apply new cairo syntax for Contract storage (Previously #959, then #960)

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc
Clarification and edits in Data availability
[Data availability](https://starknet-io.github.io/starknet-docs/pr-949/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/949)
=> docs: Clarification and edits in Data availability

components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/978)
=> fix: Minor edits in approach.adoc

.github/workflows/delete_preview.yml, .github/workflows/pull_request.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/980)
=> chore: Debugging delete preview workflow

components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/981)
=> fix: More minor changes to Starknet account interface.

.github/workflows/delete_preview.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/983)
=> chore: Debugging delete preview workflow 3

components/Starknet/modules/architecture_and_concepts/nav.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/985)
=> fix: Update Starknet account interface in TOC

.github/workflows/delete_preview.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/986)
=> chore: Debugging delete preview workflow4

components/Starknet/modules/architecture_and_concepts/pages/Accounts/approach.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/987)
=> fix: Minor edit in approach.adoc

.github/workflows/delete_preview.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/988)
=> chore: Update delete_preview.yml

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/cairo-and-sierra.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/989)
=> fix: minor edit

components/Starknet/modules/tools/pages/api-services.adoc
Fixes a broken link to the Infura RPC provider
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/993)
=> docs: fix broken Infura rpc link (was #992)

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/995)
=> fix: Minor edit in Contract classes

README.adoc
hello 
I fixed some typos in the documentation
I hope it helps.
Best regards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/999)
=> fix typos 

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/universal-deployer.adoc
This PR adds a section for the Universal Deployer Contract
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/996)
=> docs: add UDC section

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc, components/Starknet/modules/architecture_and_concepts/partials/snippet_transaction_admonition.adoc, components/Starknet/modules/architecture_and_concepts/partials/snippet_transaction_fields_master_table.adoc, components/Starknet/modules/architecture_and_concepts/partials/snippet_transaction_params.adoc, components/Starknet/modules/architecture_and_concepts/partials/snippet_v3_max_price_sidebar.adoc
[Transaction types](https://starknet-io.github.io/starknet-docs/pr-946/documentation/architecture_and_concepts/Network_Architecture/transactions/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/946)
=> docs: v0.13.0 information

.github/workflows/delete_preview.yml, .github/workflows/pull_request.yml
Tidying up delete_preview.yml and pull_request.yml.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1017)
=> chore: Tidying up delete_preview.yml and pull_request.yml.

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1015)
=> fix: Change `declare` to `DECLARE` in contract-classes.adoc

components/Starknet/modules/tools/pages/starkgate-bridge.adoc, components/Starknet/modules/tools/partials/snippet_backwards_compatibiity_note.adoc
Add table with list of bridged tokens
[StarkGate bridge overview](https://starknet-io.github.io/starknet-docs/pr-1009/documentation/tools/starkgate-bridge/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1009)
=> docs: Add table with list of bridged tokens

.github/workflows/pull_request.yml
Add debug messages to deploy-review step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1019)
=> chore: Add debug messages to deploy-review step.

components/Starknet/modules/starknet_versions/pages/version_notes.adoc, playbook.yml
Update footer with 0.13.0 on Sepolia and Goerli.
[Starknet release notes](https://starknet-io.github.io/starknet-docs/pr-1024/documentation/starknet_versions/version_notes/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1024)
=> feat: 0.13.0 now on Goerli and Sepolia

components/Starknet/modules/starknet_versions/pages/deprecated.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, playbook.yml
Update Starknet status: 0.12.3 on Mainnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1028)
=> docs: Update Starknet status: 0.12.3 on Mainnet

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/token-bridge.adoc
Remove TVL from StarkGate Overview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1029)
=> docs: Remove TVL from StarkGate Overview

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/starkgate-estimating_fees.adoc, components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
Added estimateDepositFeeWei and estimateEnrollmentFeeWei functions in function reference and topic on how to estimate fees, which points to these functions.
* [Estimating StarkGate fees](https://starknet-io.github.io/starknet-docs/pr-1031/documentation/#starknet-estimate_fee.adoc)
* [estimateDepositFeeWei](https://starknet-io.github.io/starknet-docs/pr-1031/documentation/tools/starkgate_function_reference/#estimateDepositFeeWei)
* [estimateEnrollmentFeeWei](https://starknet-io.github.io/starknet-docs/pr-1031/documentation/tools/starkgate_function_reference/#estimateEnrollmentFeeWei)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1031)
=> docs: Added estimateDepositFeeWei and estimateEnrollmentFeeWei functions in function reference.

.htaccess
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1035)
=> fix: .htaccess has incorrect redirects for StarkGate dev guide

components/Starknet/modules/tools/pages/api-services.adoc
This PR adds BlockPI Network to API services
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1034)
=> Docs: Add BlockPI to API services

components/Starknet/modules/tools/pages/api-services.adoc
Add Reddio as RPC provider
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1033)
=> docs: Update api-services.adoc add Reddio as RPC provider

components/Starknet/modules/tools/pages/api-services.adoc
Add DRPC.org to the RPC services list
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1044)
=> Update api-services.adoc with DRPC.org

components/Starknet/modules/tools/pages/api-services.adoc
adding Blockpi Starknet public endpint 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1039)
=> Update api-services.adoc  add blockpi public endpoint

components/Starknet/modules/tools/pages/api-services.adoc
This PR adds Dwellir to API services and adds a link for Nethermind, contributing to organization in the view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1037)
=> Docs: Add Dwellir to API services and Add link for Nethermind

components/Starknet/modules/starknet_versions/pages/juno_versions.adoc
Add latest Juno release notes.
file:///home/user/repos/starknet-docs/public_html/documentation/starknet_versions/juno_versions/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1036)
=> docs: add juno release notes

components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism-pre-v0.13.0.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/on-chain-data.adoc
Fixed bugs in formulas on Gas and transaction fees. Addresses Monday item [*[S][Bug]Fix incorrect cost of deployment on the fees page*](https://starkware.monday.com/boards/2575505837/views/83871033/pulses/5678915361)
- [Gas and transaction fees](https://starknet-io.github.io/starknet-docs/pr-1027/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/)
- [Data availability](https://starknet-io.github.io/starknet-docs/pr-1027/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1027)
=> Fix: Fixed bugs in formulas on Gas and transaction fees. Update fees and formulas

components/Starknet/modules/tools/pages/api-services.adoc
Fixed link to GetBlock's service.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1049)
=> Update api-services.adoc GetBlock link

components/Starknet/modules/tools/pages/api-services.adoc
Added column on multi-version support in table of API providers
[Full nodes and API services](https://starknet-io.github.io/starknet-docs/pr-1052/documentation/tools/api-services/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1052)
=> docs: Added column on multi-version support in table of API providers

.github/workflows/pull_request.yml, _typos.toml, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transaction-life-cycle.adoc, components/Starknet/modules/cli/pages/starkli.adoc, components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc
* fix: several typos in the documentation
* feat: add codespell linter workflow for CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1007)
=> chore: add codespell linter workflow for CI (was #953)

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc
Fixing the following build errors:
```
[15:20:50.681] ERROR (asciidoctor): merkle_patricia_trie sections do not support nested sections
file: /home/runner/work/starknet-docs/starknet-docs/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc:125
source: /home/runner/work/starknet-docs/starknet-docs (branch: HEAD <worktree> | start path: components/Starknet)
[15:20:50.6[8](https://github.com/starknet-io/starknet-docs/actions/runs/7348937276/job/20007961080#step:5:9)6] ERROR (asciidoctor): merkle_patricia_trie sections do not support nested sections
file: /home/runner/work/starknet-docs/starknet-docs/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/starknet-state.adoc:150
source: …
```
=> Fix: Build errors in Starknet state

.github/workflows/pull_request.yml
ci: delete the dependency relationship between jobs.
resolves #954
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1055)
=> ci: delete the dependency relationship between jobs

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/algolia-indexing.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, README.adoc, contributing_to_docs/setting_up_environment.adoc, playbook.yml
In prep for moving the default branch from `master` to `main`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1050)
=> chore: Changed Starknet docs `master` branch to `main` in yml files and .adoc files

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-classes.adoc
Added IMPORTANT admonition to call out important text.
[Contract classes](https://starknet-io.github.io/starknet-docs/pr-1058/documentation/architecture_and_concepts/Smart_Contracts/contract-classes/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1058)
=> docs: Added IMPORTANT admonition to call out important text.

components/Starknet/modules/tools/pages/ref_block_explorers.adoc
This PR adds NFTScan to block explorers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1056)
=> Docs: Add NFTScan to block explorers

.github/workflows/push.yml, components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/important_addresses.adoc, components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
Made casing of Starknet Core Contract uniform, matching what is shown in Etherscan.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1059)
=> fix: Made casing of Starknet Core Contract uniform, matching what is shown in Etherscan.

.github/ISSUE_TEMPLATE/feature_request.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1060)
=> Chore: Change default assignee for feature requests to stoobie

.github/ISSUE_TEMPLATE/bug_report.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1061)
=> Chore: Change default assignee for bug reports to stoobie

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
Improve Google results and clarify that this reference includes events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1063)
=> fix: Update title and add :description: to StarkGate function and event reference

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/starknet-events.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1064)
=> fix: Changed code highlighting from js to cairo in Emitting events

components/Starknet/modules/starknet_versions/pages/deprecated.adoc
[Deprecated features](https://starknet-io.github.io/starknet-docs/pr-1068/documentation/starknet_versions/deprecated/#deprecated_features)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1068)
=> fix: Update Goerli end-of-support until at least end of Q1 2024

components/Starknet/modules/architecture_and_concepts/partials/snippet_transaction_fields_master_table.adoc
Update units of `L1_gas` resource to fri.
https://starknet-io.github.io/starknet-docs/pr-1069/documentation/architecture_and_concepts/Network_Architecture/transactions/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1069)
=> Update snippet_transaction_fields_master_table.adoc with L1_gas units

components/Starknet/modules/starknet_versions/pages/version_notes.adoc, playbook.yml
Update: 0.13.0 is now on Mainnet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1073)
=> Update: Starknet 0.13.0 is now on Mainnet

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
Fixing a few discrepancies in 0.13.0 fee docs
https://starknet-io.github.io/starknet-docs/pr-1078/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1078)
=> fix: discrepancies in 0.13.0 fee docs

components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc
Originally this was PR#1077
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1080)
=> fix: Update declare_a_smart_contract.adoc

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
Fix Block limit (Cairo steps) in Update limits_and_triggers.adoc.
[Current limits](https://starknet-io.github.io/starknet-docs/pr-1082/documentation/tools/limits_and_triggers/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1082)
=> Fix: Block limit (Cairo steps) in Update limits_and_triggers.adoc

contributing_to_docs/doc_guidelines.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1089)
=> Added basic writing guideline summary

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1120)
=> Update table title in limits_and_triggers.adoc to say "Starknet current limits"

components/Starknet/modules/tools/pages/api-services.adoc
This PR address #1121.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1122)
=> docs: Add NOWNodes to list of API providers.

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/architecture_and_concepts/nav.adoc, components/Starknet/modules/architecture_and_concepts/pages/Economics-of-Starknet.adoc
Describing the economics of Starknet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1129)
=> docs: Steve/economics of starknet

components/Starknet/modules/architecture_and_concepts/pages/Economics-of-Starknet.adoc
Added Description and Keywords.
[The Economics of Starknet](https://starknet-io.github.io/starknet-docs/pr-1132/documentation/architecture_and_concepts/Economics-of-Starknet/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1132)
=> docs: Added metadata to Economics

components/Starknet/modules/architecture_and_concepts/pages/Economics-of-Starknet.adoc
=> docs: Updates to Economics-of-Starknet.adoc.

components/Starknet/modules/architecture_and_concepts/pages/Economics-of-Starknet.adoc
Changing "on chain" to "onchain".
=> on chain to onchain in Update Economics-of-Starknet.adoc

components/Starknet/modules/architecture_and_concepts/pages/Cryptography/hash-functions.adoc, components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc, components/Starknet/modules/starknet_versions/pages/version_notes.adoc, components/Starknet/modules/tools/pages/api-services.adoc, components/Starknet/modules/tools/pages/starkgate-bridge.adoc, components/Starknet/modules/tools/pages/starkgate_architecture.adoc
The official name of the software platform is _GitHub_. 
=> fix: Changed Github to GitHub

components/Starknet/modules/architecture_and_concepts/pages/Economics-of-Starknet.adoc
Adjusting table to optimize for mobile phone viewing
=> Fix: Adjusting table to optimize for mobile phone viewing

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
=> Update version_notes.adoc with supported Cairo versions

.github/workflows/pull_request.yml
Fix workflow for sending comment to PR by bot
=> fix: workflow for sending comment to PR

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-abi.adoc, playbook.yml
Testing  [Update highlight.js and highlightjs-cairo plugin. #32](https://github.com/starknet-io/starknet-docs-antora-ui/pull/32)
[Contract ABI](https://starknet-io.github.io/starknet-docs/pr-1153/documentation/architecture_and_concepts/Smart_Contracts/contract-abi/)
=> fix: Testing highlightjs-cairo v4.0 in starknet-docs-antora-ui

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
Removing an extra 0 from the step costs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1166)
=> fix: step cost

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1170)
=> fix: Update fee-mechanism.adoc

contributing_to_docs/starknet_docs_style_guide.adoc
Additions:
* EIP-<num>
* STRK
* fri (units of STRK)
* g-fri
https://github.com/starknet-io/starknet-docs/blob/steve/style_guide_additions/contributing_to_docs/starknet_docs_style_guide.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1161)
=> chore: Update starknet_docs_style_guide.adoc

components/Starknet/modules/tools/pages/api-services.adoc
Add All That Node to the API list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1178)
=> Update api-services.adoc with All That Node

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/system-calls-cairo1.adoc
minor fix of typeface of validate_* functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1179)
=> fix: Fix typeface of `validate_*` functions

components/Starknet/modules/architecture_and_concepts/pages/Accounts/deploying_new_accounts.adoc, components/Starknet/modules/architecture_and_concepts/pages/Accounts/validate_and_execute.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1183)
=> fix: Added NOTE formatting

.github/workflows/push.yml
Reverts starknet-io/starknet-docs#1184
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1185)
=> Revert "fix: Upload to prod server not working"

components/Starknet/modules/tools/pages/starkgate_architecture.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1149)
=> docs: Add short section about legacy bridge vs 2.0 multi-bridge support

components/Starknet/modules/tools/pages/starkgate_architecture.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1190)
=> fix: show (R) instead of registered symbol

components/Starknet/modules/quick_start/pages/set_up_an_account.adoc
Update link to Sepolia faucets instead of Goerli
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1195)
=> Update set_up_an_account.adoc with Sepolia faucets

components/Starknet/modules/tools/pages/limits_and_triggers.adoc
Update new limits and fix typo.
[Current limits](https://starknet-io.github.io/starknet-docs/pr-1194/documentation/tools/limits_and_triggers/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1194)
=> docs: Update limits_and_triggers.adoc

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1196)
=> fix: Release notes: `timestamp` should be `block_timestamp`.

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
Minor grammatical edit. No technical info is changed.
[Gas and transaction fees](https://starknet-io.github.io/starknet-docs/pr-1206/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1206)
=> fix: Minor edit in fee-mechanism.adoc

components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/fee-mechanism.adoc
Minor edit. No technical information changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1207)
=> Minor edit in fee-mechanism.adoc

components/Starknet/modules/tools/pages/starkgate_function_reference.adoc
Update StarkGate contract links from v2.0 to v2.0.1
[StarkGate function and event reference](https://starknet-io.github.io/starknet-docs/pr-1213/documentation/tools/starkgate_function_reference/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1213)
=> docs: Update StarkGate contract links from v2.0 to v2.0.1

contributing_to_docs/starknet_docs_style_guide.adoc
Add Starknet Core Contract to starknet_docs_style_guide.adoc
https://github.com/starknet-io/starknet-docs/blob/steve/style_guide/Starknet_Core_Contract/contributing_to_docs/starknet_docs_style_guide.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1215)
=> chore: Add Starknet Core Contract to starknet_docs_style_guide.adoc

components/Starknet/modules/architecture_and_concepts/nav.adoc
Promote everything in TOC under Starknet architecture one level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1216)
=> docs. Promote everything in TOC under `Starknet architecture` one level.

components/Starknet/modules/starknet_versions/pages/version_notes.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1218)
=> fix: Update incorrect year in version_notes.adoc

components/Starknet/modules/starknet_versions/pages/version_notes.adoc, playbook.yml
Update footer for Mainnet 0.13.1.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1220)
=> docs: Updates for Mainnet 0.13.1.1

components/Starknet/modules/tools/pages/devtools.adoc
starknet-devnet is no longer in development. starknet-devnet-rs has replaced it.
Additionally,  this topic no longer needs to be shared, so the source is now directly coded instead of being in docs-common-content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1219)
=> docs: Update devtools.adoc

components/Starknet/modules/tools/pages/dai_token_migration.adoc
Added more swap options, as per request from Maxime.
[Migrating DAI v0 to DAI](https://starknet-io.github.io/starknet-docs/pr-1237/documentation/tools/dai_token_migration/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1237)
=> docs: Update dai_token_migration.adoc with other Swap options

components/Starknet/modules/ROOT/pages/index.adoc
Fix typos in docs home page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1251)
=> Fix: Typos in docs home page

README.adoc
The title says it all.
https://github.com/starknet-io/starknet-docs/tree/steve/add-shields-to-README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1254)
=> chore: Add shields to README.adoc

components/Starknet/modules/tools/pages/api-services.adoc
Adding OMNIA to the RPC provider list
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1259)
=> Update api-services.adoc with OMNIA

components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/cairo-builtins.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1260)
=> fix: Prettify link.

components/Starknet/modules/tools/pages/starkgate-bridge.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1262)
=> fix: Change redundant id

.htaccess
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1265)
=> fix: Update .htaccess to add redirects to transactions page

components/Starknet/modules/tools/pages/devtools.adoc
Add Web3.js plugin to list of SDKs
https://starknet-io.github.io/starknet-docs/pr-1267/documentation/tools/devtools/#sdks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1267)
=> docs: Add Web3.js plugin to list of SDKs

.htaccess
Added missing line to .htaccess.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1269)
=> chore: Added missing line to .htaccess

components/Starknet/modules/ROOT/partials/snippet-note-content-from-sn-book.adoc
Add a snippet with this note:
"This topic previously appeared in the Starknet Book."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1274)
=> chore: Add a snippet with a note indicating that content was previously in the Starknet Book

playbook.yml
This PR references the `dev-survey-banner` branch in starknet-docs-antora-ui.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1280)
=> feat: Publish dev survey banner

playbook.yml
Moved survey link header under breadcrumbs, Added dark version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1281)
=> feat: Publish updated dev survey banner

components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1283)
=> Update api-services.adoc with Lava's multiple endpoints

components/Starknet/modules/tools/pages/api-services.adoc
Add [Juno AWS Node Runner](https://aws-samples.github.io/aws-blockchain-node-runners/docs/Blueprints/Starknet) to the docs.
[Full nodes and API services](https://starknet-io.github.io/starknet-docs/pr-1279/documentation/tools/api-services/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1279)
=> docs: Add Juno AWS Node Runner

components/Starknet/modules/tools/pages/api-services.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1287)
=> Add Zan to API providers list

components/Starknet/modules/tools/pages/starknet-book.adoc
Update outdated information about Starknet book
The Table of Contents had outdated information. Update it to reflect the contents of the book.
Update to content at https://docs.starknet.io/tools/starknet-book/ 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1297)
=> docs: Update Starknet book ToC

components/Starknet/antora.yml, components/Starknet/modules/ROOT/nav-back-matter.adoc, components/Starknet/modules/ROOT/pages/faq.adoc
[FAQ](https://starknet-io.github.io/starknet-docs/pr-1282/faq/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1282)
=> docs: add faq

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1292)
=> fix typo adding class hashes in tx v3 invoke computation

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1312)
=> fix: Added a link to info on the L1 handler tx type from the tx versions table.

components/Starknet/modules/quick-start/pages/deploy-interact-with-a-smart-contract-remix.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1316)
=> docs: Add Sn-book note to deploy-interact-with-a-smart-contract-remix.adoc

components/Starknet/modules/ROOT/nav.adoc
Commented out notational conventions.
https://starknet-io.github.io/starknet-docs/pr-1329/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1329)
=> Commented out notational conventions

components/Starknet/modules/tools/nav.adoc
Removed Juno and Pathfinder release notes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1331)
=> Removed Juno and Pathfinder release notes

components/Starknet/modules/quick-start/nav.adoc, components/Starknet/modules/quick-start/pages/using_devnet.adoc
Added instructions for using devnet to quick start and restructed accordingly.
https://starknet-io.github.io/starknet-docs/pr-1332/quick-start/using_devnet/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1332)
=> Added instructions for using devnet

playbook.yml
Chatwith test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1334)
=> Chatwith test

components/Starknet/modules/starknet-versions/pages/version-notes.adoc
Updated release notes of Starknet 0.13.2. Updated version numbers in the top table.
https://starknet-io.github.io/starknet-docs/pr-1340/starknet-versions/version-notes/#version0.13.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1340)
=> Update 0.13.2 release notes

components/Starknet/modules/tools/pages/limits-and-triggers.adoc
https://starknet-io.github.io/starknet-docs/pr-1342/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1342)
=> Update limits of v0.13.2

components/Starknet/modules/starknet-versions/pages/version-notes.adoc
Update the supported Cairo versions to <= 2.8.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1358)
=> docs: update supported cairo versions

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/messaging-reference.adoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1369)
=> l2ToL1Messages return value fix

components/Starknet/modules/tools/pages/api-services.adoc
Replace Madara instead of Deoxys.
=> Replace Deoxys with Madara in api-services.adoc

components/Starknet/modules/tools/pages/api-services.adoc
Add ZAN RPC service open API link.
https://starknet-io.github.io/starknet-docs/pr-1372/tools/api-services/
=> Add ZAN RPC service open API link

components/Starknet/modules/ROOT/pages/index.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/data-indexers.adoc
Added a section of data indexers and a link to DipDup.
https://starknet-io.github.io/starknet-docs/pr-1357/tools/data-indexers/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1357)
=> docs: added a section of data indexers and a link to DipDup

components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
Change the wording in the description of validate's limitations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1361)
=> docs: rephrase validate limitations

components/Starknet/modules/tools/pages/oracles.adoc
Add existing oracles to the oracles page.
https://starknet-io.github.io/starknet-docs/pr-1377/tools/oracles/
=> Update oracles.adoc with more oracles

components/Starknet/modules/starknet-versions/nav.adoc, components/Starknet/modules/starknet-versions/pages/deprecated.adoc, components/Starknet/modules/starknet-versions/pages/version-notes.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/important-addresses.adoc, components/Starknet/modules/tools/pages/limits-and-triggers.adoc
Restructured the "Release information" section.
=> Release info restruct

js/algolia-index.js
=> Algolia bug fix

components/Starknet/modules/staking/pages/increasing-staking.adoc
Removed operator from increasing-staking.adoc
https://starknet-io.github.io/starknet-docs/pr-1384/staking/increasing-staking/
=> Staking operator removal (increasing-staking.adoc)

components/Starknet/modules/staking/pages/overview.adoc
Updated staking/overview.adoc.
https://starknet-io.github.io/starknet-docs/pr-1390/staking/overview/
=> Staking overview update

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/block-structure.adoc
Refactored the "Block structure" section.
https://starknet-io.github.io/starknet-docs/pr-1391/architecture-and-concepts/network-architecture/block-structure/
=> Block structure refactor

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/block-structure.adoc
Fixed links in block-structure.adoc.
https://starknet-io.github.io/starknet-docs/pr-1397/architecture-and-concepts/network-architecture/block-structure/
=> block-structure.adoc minor fix

.github/workflows/push.yml
Added `.htaccess` to `push.yml`.
N/A.
=> Added .htaccess to CI

components/Starknet/modules/quick-start/pages/environment-setup.adoc
Updating the env setup instructions to use asdf and not scarb script
If the PR is related to an open issue, please also link to it.
https://starknet-io.github.io/starknet-docs/pr-1398/quick-start/environment-setup/
=> Update scarb installation to use asdf

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/fee-mechanism.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
Refactored the "Gas and transaction fees" page.
https://starknet-io.github.io/starknet-docs/pr-1409/architecture-and-concepts/network-architecture/fee-mechanism/
=> Gas and transaction fees refactor

components/Starknet/modules/tools/pages/limits-and-triggers.adoc
Update testnet version to v0.13.3.
https://starknet-io.github.io/starknet-docs/pr-1408/tools/limits-and-triggers/
=> Update Starknet version to v0.13.3

components/Starknet/modules/quick-start/pages/environment-setup.adoc
A rebased version of #1410. 
https://starknet-io.github.io/starknet-docs/pr-1413/quick-start/environment-setup/
=> PR 1410 rebased

components/Starknet/modules/starknet-versions/pages/version-notes.adoc
Added v0.13.3 release notes.
https://starknet-io.github.io/starknet-docs/pr-1400/starknet-versions/version-notes/#version0.13.3
=> v0.13.3 release notes

components/Starknet/modules/staking/pages/increasing-staking.adoc
Removed wrong bullet point in the prerequisites.
https://starknet-io.github.io/starknet-docs/pr-1415/staking/increasing-staking/
=> Minor fix in increasing-staking.adoc

components/Starknet/modules/quick-start/pages/environment-setup.adoc
Refactored "Setting up your environment".
https://starknet-io.github.io/starknet-docs/pr-1414/quick-start/environment-setup/
=> Enviorment setup refactor

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/compatibility.adoc
Refactored #1347. 
https://starknet-io.github.io/starknet-docs/pr-1417/tools/compatibility/
=> PR 1347 refactor

components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
Fixed a minor issue in "Account interface function reference".
https://starknet-io.github.io/starknet-docs/pr-1419/architecture-and-concepts/accounts/account-functions/#limitations_of_validation
=> Account interface function reference minor fix

README.adoc
Fixed some bugs to display the link
=> docs: readme

components/Starknet/modules/staking/pages/entering-staking.adoc, components/Starknet/modules/staking/pages/overview.adoc, components/Starknet/modules/tools/nav.adoc
Added details for staking on mainnet.
- https://starknet-io.github.io/starknet-docs/pr-1425/staking/overview/#contract-addresses
- https://starknet-io.github.io/starknet-docs/pr-1425/staking/entering-staking/
=> Staking on mainnet

components/Starknet/modules/staking/pages/entering-staking.adoc
Changed "pre-approve" to "approve" in "Becoming a Validator".
https://starknet-io.github.io/starknet-docs/pr-1434/staking/entering-staking/
=> Minor fix in "Becoming a Validator"

components/Starknet/modules/staking/pages/entering-staking.adoc
Changed one remaining occurrence of "pre-approval" to "approval".
https://starknet-io.github.io/starknet-docs/pr-1435/staking/entering-staking/
=> Minor fix "Becoming a validator"

components/Starknet/modules/staking/pages/entering-staking.adoc
Added links to block explorer and CLI tools in "Becoming a Validator".
https://starknet-io.github.io/starknet-docs/pr-1438/staking/entering-staking/
=> Added links in "Becoming a Validator"

components/Starknet/modules/tools/pages/limits-and-triggers.adoc
Update Starknet mainnet version to v0.13.3.
https://starknet-io.github.io/starknet-docs/pr-1445/tools/limits-and-triggers/
=> Update Starknet mainnet version to v0.13.3

components/Starknet/modules/quick-start/pages/environment-setup.adoc, components/Starknet/modules/quick-start/pages/set-up-an-account.adoc
Refactored the "Setting up an account" page in the "Quickstart" section.
https://starknet-io.github.io/starknet-docs/pr-1469/quick-start/set-up-an-account/
=> Setting up account refactor

components/Starknet/modules/staking/pages/entering-staking.adoc
Added an "important" block with info about the validator survey to the "Becoming a Validator" page.
If the PR is related to an open issue, please also link to it.
https://starknet-io.github.io/starknet-docs/pr-1473/staking/entering-staking/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1473)
=> Validator survey important block

components/Starknet/modules/staking/pages/architecture.adoc, components/Starknet/modules/staking/pages/claiming-rewards.adoc, components/Starknet/modules/staking/pages/delegating-stake.adoc, components/Starknet/modules/staking/pages/entering-staking.adoc, components/Starknet/modules/staking/pages/exiting-staking.adoc, components/Starknet/modules/staking/pages/increasing-staking.adoc, components/Starknet/modules/staking/pages/managing-staking-and-delegation-operations.adoc, components/Starknet/modules/staking/pages/overview.adoc, components/Starknet/modules/staking/pages/staking-events-and-read-functions.adoc, components/Starknet/modules/staking/pages/switching-delegation-pools.adoc, components/Starknet/modules/staking/partials/snippet-important-staking-survey.adoc
Added the important block about the staking survey to all staking pages.
https://starknet-io.github.io/starknet-docs/pr-1476/staking/overview/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/architecture/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/entering-staking/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/increasing-staking/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/claiming-rewards/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/claiming-rewards/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/switching-delegation-pools/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/exiting-staking/
https://starknet-io.github.io/starknet-docs/pr-1476/staking/managing-staking-and-delegation-operations/ …
=> Staking survey cont.

components/Starknet/modules/ROOT/nav_glossary.adoc, components/Starknet/modules/starknet-versions/pages/version-notes.adoc
Added pre-release notes for v0.13.4.
https://starknet-io.github.io/starknet-docs/pr-1482/starknet-versions/version-notes/#version0.13.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1482)
=> v0.13.4 pre-release notes

components/Starknet/modules/ROOT/pages/chain-info.adoc
Added the storage updates per transaction limit under "Current limits" in the "Chain info" page, finalizing #1479 and closing #1321. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1485)
=> Add storage updates limit

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/audit.adoc
Refactored the "Auditors" page in the "Ecosystem" section.
https://starknet-io.github.io/starknet-docs/pr-1490/tools/audit/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1490)
=> Auditors refactor

components/Starknet/modules/quick-start/nav.adoc, components/Starknet/modules/quick-start/pages/next-steps.adoc
Added a "Community guides" subsection under the "Guides" section.
https://starknet-io.github.io/starknet-docs/pr-1492/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1492)
=> Community guides subsection

components/Starknet/modules/staking/pages/architecture.adoc, components/Starknet/modules/staking/pages/claiming-rewards.adoc, components/Starknet/modules/staking/pages/delegating-stake.adoc, components/Starknet/modules/staking/pages/entering-staking.adoc, components/Starknet/modules/staking/pages/exiting-staking.adoc, components/Starknet/modules/staking/pages/increasing-staking.adoc, components/Starknet/modules/staking/pages/managing-staking-and-delegation-operations.adoc, components/Starknet/modules/staking/pages/overview.adoc, components/Starknet/modules/staking/pages/staking-events-and-read-functions.adoc, components/Starknet/modules/staking/pages/switching-delegation-pools.adoc, components/Starknet/modules/staking/partials/snippet-important-staking-survey.adoc, components/Starknet/modules/staking/partials/snippet-important-staking-v2.adoc
Added a snippet about staking v2 to all staking pages.
https://starknet-io.github.io/starknet-docs/pr-1494/staking/overview/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/entering-staking/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/increasing-staking/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/claiming-rewards/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/delegating-stake/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/switching-delegation-pools/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/exiting-staking/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/managing-staking-and-delegation-operations/
https://starknet-io.github.io/starknet-docs/pr-1494/staking/staking-events-and-read-function …
=> Staking v2 important snippet

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/audit.adoc
Added "Security platforms" to the "Auditors" page in the "Ecosystem" section.
https://starknet-io.github.io/starknet-docs/pr-1495/tools/audit/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1495)
=> Ecosystem security platforms

components/Starknet/modules/quick-start/pages/environment-setup.adoc
Fix a typo in setup docs
Fixed a typo spotted in the setup docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1496)
=> Fix typo in environment setup

components/Starknet/modules/ROOT/pages/index.adoc
Refactored the "Overview" page.
https://starknet-io.github.io/starknet-docs/pr-1498/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1498)
=> Overview Refactor

components/Starknet/modules/tools/pages/audit.adoc
Refactored subsection in the "Auditors" page.
https://starknet-io.github.io/starknet-docs/pr-1500/tools/audit/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1500)
=> Auditors mini-refactor

components/Starknet/modules/starkgate/pages/function-reference.adoc, components/Starknet/modules/starkgate/pages/overview.adoc
Minorly refactored StarkGate's "Overview".
https://starknet-io.github.io/starknet-docs/pr-1501/starkgate/overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1501)
=> StarkGate overview minor refactor

components/Starknet/modules/quick-start/nav.adoc
Added the Cairo book to "Community guides".
https://starknet-io.github.io/starknet-docs/pr-1503/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1503)
=> Cairo book community guide

components/Starknet/modules/tools/pages/audit.adoc
Minorly refactored `audit.adoc`.
https://starknet-io.github.io/starknet-docs/pr-1505/tools/audit/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1505)
=> audit.adoc minor refactor

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/api-services.adoc
Refactored `api-services.adoc` differently than #1504. 
https://starknet-io.github.io/starknet-docs/pr-1507/tools/api-services/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1507)
=> api-services.adoc refactor v2

.htaccess, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/indexers-enhanced-apis.adoc
Changed "Enhanced API providers" to Enhanced APIs".
https://starknet-io.github.io/starknet-docs/pr-1514/tools/indexers-enhanced-apis/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1514)
=> Enhanced APIs minor fix

components/Starknet/modules/ROOT/pages/chain-info.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/messaging-mechanism.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc, components/Starknet/modules/architecture-and-concepts/pages/nodes.adoc, components/Starknet/modules/architecture-and-concepts/pages/provers-overview.adoc, components/Starknet/modules/architecture-and-concepts/pages/solidity-verifier.adoc, components/Starknet/modules/quick-start/pages/sepolia.adoc, components/Starknet/modules/staking/pages/entering-staking.adoc, components/Starknet/modules/starknet-versions/pages/version-notes.adoc
This PR handles existing errors in the build_local_site script.
https://starknet-io.github.io/starknet-docs/pr-1517/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1517)
=> fix: broken xrefs

components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
Minorly fixed secpr1.
https://starknet-io.github.io/starknet-docs/pr-1522/architecture-and-concepts/smart-contracts/system-calls-cairo1/#secp256r1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1522)
=> secpr1 minor fixes

components/Starknet/modules/architecture-and-concepts/pages/network-architecture/data-availability.adoc
Added info to the DA page on effects of v0.13.3 and v0.13.4, alongside an overall refactor.
https://starknet-io.github.io/starknet-docs/pr-1521/architecture-and-concepts/network-architecture/data-availability/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1521)
=> v0.13.3+v0.13.4 DA

components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
Applied minor fixes to secp256k1 syscalls.
https://starknet-io.github.io/starknet-docs/pr-1538/architecture-and-concepts/smart-contracts/system-calls-cairo1/#secp256k1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1538)
=> secp256k1 minor fixes

components/Starknet/modules/architecture-and-concepts/nav.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/fee-mechanism.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/os.adoc
v2 of #1520. 
https://starknet-io.github.io/starknet-docs/pr-1544/architecture-and-concepts/network-architecture/fee-mechanism/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1544)
=> Fee mechanism refactor v2

components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/devtools/building-dapps.adoc, components/Starknet/modules/tools/pages/devtools/coding-in-cairo.adoc, components/Starknet/modules/tools/pages/devtools/creating-ai-agents.adoc, components/Starknet/modules/tools/pages/devtools/interacting-with-starknet.adoc, components/Starknet/modules/tools/pages/devtools/overview.adoc, components/Starknet/modules/tools/pages/devtools/running-devnets.adoc, components/Starknet/modules/tools/pages/devtools/writing-smart-contracts.adoc
Added "Tools for creating AI agents" page to "Tooling" section.
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/overview/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/coding-in-cairo/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/writing-smart-contracts/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/building-dapps/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/interacting-with-starknet/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/running-devnets/
https://starknet-io.github.io/starknet-docs/pr-1546/tools/devtools/creating-ai-agents/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> New AI agents tooling page

components/Starknet/modules/ecosystem/nav.adoc, components/Starknet/modules/ecosystem/pages/overview.adoc, components/Starknet/modules/ecosystem/pages/wallets-onramps.adoc, components/Starknet/modules/quick-start/pages/next-steps.adoc, components/Starknet/modules/tools/pages/overview.adoc
Various minor fixes to recent PRs.
https://starknet-io.github.io/starknet-docs/pr-1549/tools/overview/
https://starknet-io.github.io/starknet-docs/pr-1549/ecosystem/overview/
https://starknet-io.github.io/starknet-docs/pr-1549/ecosystem/wallets-onramps/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1549)
=> Minor fixes

components/Starknet/modules/resources/pages/chain-info.adoc, components/Starknet/modules/starkgate/pages/overview.adoc
Moved StarkGate token addresses to the "Chain info" page.
https://starknet-io.github.io/starknet-docs/pr-1550/starkgate/overview/
https://starknet-io.github.io/starknet-docs/pr-1550/resources/chain-info/#important_addresses
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1550)
=> SG addresses move

README.adoc
"Nativgate" → "Navigate"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1552)
=> docs: typo fix

js/algolia-index.js
Delete old index to get rid of old deleted pages and get a new up-to-date index.
https://starknet-io.github.io/starknet-docs/pr-1558/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1558)
=> Update algolia-index.js for new indexing

components/Starknet/modules/architecture-and-concepts/nav.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/coding-in-cairo.adoc, components/Starknet/modules/tools/pages/core-tools.adoc, components/Starknet/modules/tools/pages/interacting-with-starknet.adoc, components/Starknet/modules/tools/pages/overview.adoc, components/Starknet/modules/tools/pages/running-devnets.adoc, components/Starknet/modules/tools/pages/writing-smart-contracts.adoc
Continued refactoring the "Tooling" section.
https://starknet-io.github.io/starknet-docs/pr-1563/tools/overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1563)
=> Tooling refactor cont.

components/Starknet/modules/resources/pages/compatibility.adoc
Updating the compatibility table with tools released with 0.8 support
https://starknet-io.github.io/starknet-docs/pr-1566/resources/compatibility/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1566)
=> Update tools compatible with 0.8

components/Starknet/modules/tools/pages/interacting-with-starknet.adoc
This PR adds the Starknet Deploy tool to the "Tools for Interacting with Starknet" section.
https://starknet-io.github.io/starknet-docs/pr-1560/tools/interacting-with-starknet/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1560)
=> Add Starknet Deploy to "Tools for Interacting with Starknet"

components/Starknet/modules/resources/pages/compatibility.adoc
Add JVM version compatible with 0.8.0 and other small version fixes
https://starknet-io.github.io/starknet-docs/pr-1567/resources/compatibility/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1567)
=> Update compatibility table with JVM, and other fixes

components/Starknet/modules/staking/pages/claiming-rewards.adoc, components/Starknet/modules/staking/pages/delegating-stake.adoc, components/Starknet/modules/staking/pages/entering-staking.adoc, components/Starknet/modules/staking/pages/exiting-staking.adoc, components/Starknet/modules/staking/pages/increasing-staking.adoc, components/Starknet/modules/staking/pages/managing-staking-and-delegation-operations.adoc, components/Starknet/modules/staking/pages/overview.adoc, components/Starknet/modules/staking/pages/staking-events-and-read-functions.adoc, components/Starknet/modules/staking/pages/switching-delegation-pools.adoc, components/Starknet/modules/staking/partials/snippet-important-staking-architecture.adoc
Continued updating the staking guides docs to staking phase 2, in a different way than  #1569 and #1556. 
https://starknet-io.github.io/starknet-docs/pr-1570/staking/overview/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/entering-staking/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/increasing-staking/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/claiming-rewards/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/delegating-stake/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/switching-delegation-pools/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/exiting-staking/
https://starknet-io.github.io/starknet-docs/pr-1570/staking/managing-staking-and-delegation-operations/ …
=> Staking p2 cont

components/Starknet/modules/ecosystem/pages/auditors-security-platforms.adoc
add Oak Security to list of auditors
https://starknet-io.github.io/starknet-docs/pr-1581/ecosystem/auditors-security-platforms/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1581)
=> add Oak Security to list of auditors

components/Starknet/modules/ecosystem/pages/auditors-security-platforms.adoc
add Defense by Thesis to list of auditors
https://docs.starknet.io/ecosystem/auditors-security-platforms/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1580)
=> add Defense by Thesis

components/Starknet/modules/tools/pages/building-dapps.adoc
I have added the Chipi SDK documentation to the tools section for building Starknet dApps. The entry includes:
Link to the official documentation
Brief description of its main features
Information about its invisible wallet functionality
dApp development simplification
https://starknet-io.github.io/starknet-docs/pr-1582/tools/building-dapps/#chipi_sdk
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1582)
=> add chipi sdk to docs

components/Starknet/modules/quick-start/pages/devnet.adoc, components/Starknet/modules/quick-start/pages/environment-setup.adoc, components/Starknet/modules/quick-start/pages/sepolia.adoc
Replaced Starkli with Foundry in "Quickstart".
https://starknet-io.github.io/starknet-docs/pr-1579/quick-start/devnet/
https://starknet-io.github.io/starknet-docs/pr-1579/quick-start/sepolia/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1579)
=> Quickstart Starkli->Foundry

components/Starknet/modules/quick-start/pages/environment-setup.adoc
Added a windows installation guide.
https://starknet-io.github.io/starknet-docs/pr-1572/quick-start/environment-setup/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1572)
=> Windows installation guide

components/Starknet/modules/ecosystem/pages/indexers-enhanced-apis.adoc
NFTScan removed Starknet support, removing them from the docs. 
https://starknet-io.github.io/starknet-docs/pr-1585/ecosystem/indexers-enhanced-apis/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1585)
=> Update indexers-enhanced-apis.adoc - remove NFTScan

components/Starknet/modules/architecture-and-concepts/pages/accounts/deploying-new-accounts.adoc, components/Starknet/modules/architecture-and-concepts/pages/accounts/universal-deployer.adoc, components/Starknet/modules/architecture-and-concepts/pages/network-architecture/fee-mechanism.adoc
hey team ! I found simple errors and fixed them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1584)
=> docs:fix correction

components/Starknet/modules/ecosystem/pages/open-rpc-endpoints-sepolia-faucets.adoc
Update the docs with the new Starknet Foundation faucet link.
https://starknet-io.github.io/starknet-docs/pr-1586/ecosystem/open-rpc-endpoints-sepolia-faucets/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1586)
=> Update open-rpc-endpoints-sepolia-faucets.adoc with the new faucet link

.htaccess, components/Starknet/modules/resources/nav.adoc, components/Starknet/modules/tools/nav.adoc, components/Starknet/modules/tools/pages/compatibility.adoc
Moved compatability page.
https://starknet-io.github.io/starknet-docs/pr-1597/tools/compatibility/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1597)
=> Compatability move

components/Starknet/modules/resources/pages/chain-info.adoc
Denominate the chain limits in L2 gas.
https://starknet-io.github.io/starknet-docs/pr-1596/resources/chain-info/#current_limits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1596)
=> Denominate resources in L2 gas

components/Starknet/modules/guides/pages/staking-on-starknet/block-attestation.adoc, components/Starknet/modules/quick-start/pages/devnet.adoc, components/Starknet/modules/quick-start/pages/environment-setup.adoc, components/Starknet/modules/quick-start/pages/hellostarknet.adoc, components/Starknet/modules/quick-start/pages/sepolia.adoc
Checked up on the "Quickstart" guide.
https://starknet-io.github.io/starknet-docs/pr-1602/quick-start/overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1602)
=> Checkup quickstart

components/Starknet/modules/architecture-and-concepts/pages/staking.adoc, components/Starknet/modules/guides/pages/staking-on-starknet/next-steps.adoc, components/Starknet/modules/guides/pages/staking-on-starknet/pathfinder.adoc
Fixes various minor issues in Staking docs.
https://starknet-io.github.io/starknet-docs/pr-1648/guides/staking-on-starknet/pathfinder/
https://starknet-io.github.io/starknet-docs/pr-1648/guides/staking-on-starknet/next-steps/
https://starknet-io.github.io/starknet-docs/pr-1648/architecture-and-concepts/staking/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1648)
=> Staking minor fixes

components/Starknet/modules/guides/pages/staking-on-starknet/stake.adoc
Spotted and fixed a few wording hiccups:
`accumalating` - `accumulating`
https://starknet-io.github.io/starknet-docs/pr-1650/guides/staking-on-starknet/stake/#locking_strk
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1650)
=> polishing docs: error fixes for clarity

components/Starknet/modules/ecosystem/pages/fullnodes-rpc-providers.adoc
Remove chainbase from API provider list
https://starknet-io.github.io/starknet-docs/pr-1651/ecosystem/fullnodes-rpc-providers/#rpc_providers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1651)
=> Remove chainbase from API provider list

components/Starknet/modules/ecosystem/pages/fullnodes-rpc-providers.adoc
Add Spectrum to the RPC providers list
https://starknet-io.github.io/starknet-docs/pr-1652/ecosystem/fullnodes-rpc-providers/#rpc_providers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1652)
=> Add Spectrum to the RPC providers list

.htaccess, components/Starknet/modules/architecture/nav.adoc, components/Starknet/modules/architecture/pages/strk.adoc
Refactored tokenomics docs.
https://starknet-io.github.io/starknet-docs/pr-1657/architecture/strk/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1657)
=> Tokenomics refactor

components/Starknet/modules/architecture/pages/staking.adoc
Added references to the Bitcoin staking SNIP.
https://starknet-io.github.io/starknet-docs/pr-1656/architecture/staking/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1656)
=> Bitcoin staking SNIP

components/Starknet/modules/architecture/nav.adoc, components/Starknet/modules/architecture/pages/protocol-overview.adoc
Added an overview for the "Protocol" section.
https://starknet-io.github.io/starknet-docs/pr-1658/architecture/protocol-overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1658)
=> Protocol overview

modules/guides/pages/becoming-a-validator/next-steps.adoc
Minor typo fix in the validator guide's next steps.
https://starknet-io.github.io/starknet-docs/pr-1673/guides/becoming-a-validator/next-steps/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1673)
=> Minor typo fix in validator guide

modules/tools/pages/overview.adoc
Adding Dynamic to the list of tools on Starknet.
https://starknet-io.github.io/starknet-docs/pr-1670/tools/overview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1670)
=> Add Dynamic.xyz to the list of tools within the Starknet ecosystem

.github/workflows/algolia-indexing.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, .github/workflows/tag.yml
Updated actions/setup-node to v4 for better compatibility with the latest runner environments. Workflows only updated—no functional changes. Release notes: https://github.com/actions/setup-node/releases/tag/v4.0.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1624)
=> build: update setup-node to v4

modules/ecosystem/pages/overview.adoc
Update testnet faucets info
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1680)
=> Update testnet faucets info

antora.yml, modules/ROOT/pages/index.adoc, modules/ecosystem/nav.adoc, modules/ecosystem/pages/overview.adoc, modules/resources/nav.adoc, modules/resources/pages/version-notes.adoc, modules/tools/pages/overview.adoc
Refactored the ecosystem and resources sections.
https://starknet-io.github.io/starknet-docs/pr-1690/
https://starknet-io.github.io/starknet-docs/pr-1690/tools/overview/
https://starknet-io.github.io/starknet-docs/pr-1690/ecosystem/overview/
https://starknet-io.github.io/starknet-docs/pr-1690/resources/version-notes/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1690)
=> Ecosystem and resources refactor

docs.json, index.mdx, learn/intro.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1706)
=> add intro main page

learn/cheatsheets/version-notes.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1713)
=> Docs: add release notes for v0.14.1
